package specrest.codegen.go

import specrest.codegen.AuthSchemes
import specrest.ir.generated.SpecRestGenerated.*
import specrest.profile.ProfiledService

object SecurityGo:

  // sorted so that equivalent OR-alternative sets share one middleware
  def middlewareName(requiresAuth: List[String]): String =
    s"Require${requiresAuth.sorted.map(AuthSchemes.pascalName).mkString("Or")}"

  def configLines(ir: ServiceIRFull): List[List[String]] =
    AuthSchemes.credSlots(ir).map: slot =>
      val field = slot match
        case AuthSchemes.CredSlot.JwtSecret    => "JwtSecret"
        case AuthSchemes.CredSlot.JwtAlgorithm => "JwtAlgorithm"
        case AuthSchemes.CredSlot.Token(n)     => s"AuthToken${AuthSchemes.pascalName(n)}"
        case AuthSchemes.CredSlot.Key(n)       => s"AuthKey${AuthSchemes.pascalName(n)}"
        case AuthSchemes.CredSlot.BasicUsername(n) =>
          s"AuthBasic${AuthSchemes.pascalName(n)}Username"
        case AuthSchemes.CredSlot.BasicPassword(n) =>
          s"AuthBasic${AuthSchemes.pascalName(n)}Password"
      val default = slot match
        case AuthSchemes.CredSlot.JwtAlgorithm => "HS256"
        case _                                 => ""
      List(field, "string", s"`env:\"${slot.envKey}\" envDefault:\"$default\"`")

  def emit(profiled: ProfiledService, module: String): String =
    val ir       = profiled.ir
    val schemes  = svcSecurity(ir)
    val needsJwt = AuthSchemes.needsJwt(ir)

    val combos = AuthSchemes.orCombos(profiled.operations)

    val checkers    = schemes.map(checker)
    val middlewares = schemes.map(s => middleware(List(ssdName(s))))
    val comboMws    = combos.map(middleware)

    val hasBearer = schemes.exists(s =>
      ssdKind(s) match { case SsBearer(_) => true; case _ => false }
    )
    val needsSubtle = AuthSchemes.needsConstantTimeCompare(ir)
    val imports = (
      List("\"net/http\"") ++
        (if needsSubtle then List("\"crypto/subtle\"") else Nil) ++
        (if hasBearer then List("\"strings\"") else Nil)
    ).sorted
    val thirdParty =
      if needsJwt then "\n\n\tjwt \"github.com/golang-jwt/jwt/v5\"" else ""
    val configImport = s"\n\n\t\"$module/internal/config\""

    s"""|// Auto-generated by spec-to-rest. Do not edit by hand.
        |//
        |// Spec-declared security schemes (the service's security block). Each
        |// scheme gets a checker and a Require* middleware; multi-scheme
        |// requires_auth clauses get a combined middleware with OR semantics.
        |// Everything fails closed: missing credentials or missing configuration
        |// is a 401.
        |
        |package auth
        |
        |import (
        |${imports.map("\t" + _).mkString("\n")}$thirdParty$configImport
        |)${checkers.mkString}${middlewares.mkString}${comboMws.mkString}
        |""".stripMargin

  private def unauthorized: String =
    "w.Header().Set(\"WWW-Authenticate\", \"Bearer\")\n\t\t\t\twriteDetail(w, http.StatusUnauthorized, \"Unauthorized\")"

  private def middleware(names: List[String]): String =
    val checks = names
      .map(n => s"check${AuthSchemes.pascalName(n)}(cfg, r)")
      .mkString(" || ")
    val doc =
      if names.sizeIs > 1 then
        s"// ${middlewareName(names)} accepts any one of the alternative schemes."
      else s"// ${middlewareName(names)} guards a route with the '${names.head}' scheme."
    s"""|
        |
        |$doc
        |func ${middlewareName(names)}(cfg *config.Config) func(http.Handler) http.Handler {
        |	return func(next http.Handler) http.Handler {
        |		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        |			if !($checks) {
        |				$unauthorized
        |				return
        |			}
        |			next.ServeHTTP(w, r)
        |		})
        |	}
        |}""".stripMargin

  private def bearerToken: String =
    """token := ""
      |	if len(header) >= len(bearerPrefix) && strings.EqualFold(header[:len(bearerPrefix)], bearerPrefix) {
      |		token = header[len(bearerPrefix):]
      |	}""".stripMargin

  private def checker(decl: security_scheme_decl): String =
    val n = ssdName(decl)
    val p = AuthSchemes.pascalName(n)
    val body = ssdKind(decl) match
      case kind if AuthSchemes.isJwt(kind) =>
        s"""|	header := r.Header.Get("Authorization")
            |	$bearerToken
            |	if token == "" || cfg.JwtSecret == "" {
            |		return false
            |	}
            |	parsed, err := jwt.Parse(token, func(t *jwt.Token) (any, error) {
            |		return []byte(cfg.JwtSecret), nil
            |	}, jwt.WithValidMethods([]string{cfg.JwtAlgorithm}))
            |	return err == nil && parsed.Valid""".stripMargin
      case SsBearer(_) =>
        s"""|	header := r.Header.Get("Authorization")
            |	$bearerToken
            |	if cfg.AuthToken$p == "" {
            |		return false
            |	}
            |	return subtle.ConstantTimeCompare([]byte(token), []byte(cfg.AuthToken$p)) == 1""".stripMargin
      case SsApiKey(location, paramName) =>
        val extract = location match
          case "query" => s"value := r.URL.Query().Get(\"$paramName\")"
          case "cookie" =>
            s"""value := ""
               |	if c, err := r.Cookie("$paramName"); err == nil {
               |		value = c.Value
               |	}""".stripMargin
          case _ => s"value := r.Header.Get(\"$paramName\")"
        s"""|	$extract
            |	if cfg.AuthKey$p == "" {
            |		return false
            |	}
            |	return subtle.ConstantTimeCompare([]byte(value), []byte(cfg.AuthKey$p)) == 1""".stripMargin
      case SsBasic() =>
        s"""|	username, password, ok := r.BasicAuth()
            |	if !ok || cfg.AuthBasic${p}Username == "" || cfg.AuthBasic${p}Password == "" {
            |		return false
            |	}
            |	userOk := subtle.ConstantTimeCompare([]byte(username), []byte(cfg.AuthBasic${p}Username)) == 1
            |	passOk := subtle.ConstantTimeCompare([]byte(password), []byte(cfg.AuthBasic${p}Password)) == 1
            |	return userOk && passOk""".stripMargin
    s"""|
        |
        |func check$p(cfg *config.Config, r *http.Request) bool {
        |$body
        |}""".stripMargin
