.PHONY: install build dev start test typecheck prisma-generate prisma-migrate prisma-deploy

install:
	npm install

build:
	npm run build

dev:
	npm run dev

start:
	npm start

test:
	npm test

typecheck:
	npm run typecheck

prisma-generate:
	npx prisma generate

prisma-migrate:
	npx prisma migrate dev

prisma-deploy:
	npx prisma migrate deploy
