pullRequests.frequency = "@weekly"

commits.message = "deps: bump ${artifactName} from ${currentVersion} to ${nextVersion}"

pullRequests.grouping = [
  { name = "circe", title = "deps(circe): grouped bump", filter = [{ group = "io.circe" }] },
  { name = "alloy", title = "deps(alloy): grouped bump", filter = [{ group = "org.alloytools" }] },
  { name = "munit", title = "deps(munit): grouped bump", filter = [{ artifact = "munit*" }] }
]

updates.ignore = [
  { version = { contains = "-RC" } },
  { version = { contains = "-M" } },
  { version = { contains = "-alpha" } },
  { version = { contains = "-beta" } }
]
