rules = [
  DisableSyntax
  OrganizeImports
]

OrganizeImports {
  targetDialect = Scala3
  removeUnused = true
}

DisableSyntax {
  noVars = false
  noNulls = true
  noReturns = true
  noAsInstanceOf = true
  noIsInstanceOf = false
}
