version = 3.8.3
runner.dialect = scala3

maxColumn = 100
align.preset = most
align.multiline = false

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers
]

newlines.source = keep
