"""Auto-generated by spec-to-rest. Do not edit by hand."""
import atexit
import os
import secrets

import httpx
import pytest

BASE_URL = os.environ.get("SPEC_TEST_BASE_URL", "http://localhost:8000")
INPROC = os.environ.get("SPEC_TEST_INPROC") == "1"
ADMIN_TOKEN = os.environ.get("ADMIN_TOKEN", "")


if INPROC:
    # The token must be in the environment before app.config instantiates
    # Settings, which happens transitively on the app.main import below.
    if not ADMIN_TOKEN:
        ADMIN_TOKEN = secrets.token_hex(32)
        os.environ["ADMIN_TOKEN"] = ADMIN_TOKEN
    from fastapi.testclient import TestClient

    from app.main import app

    client = TestClient(app, base_url=BASE_URL)
    client.__enter__()
    atexit.register(client.__exit__, None, None, None)
else:
    client = httpx.Client(base_url=BASE_URL, timeout=10.0)
    atexit.register(client.close)

if ADMIN_TOKEN:
    client.headers["Authorization"] = f"Bearer {ADMIN_TOKEN}"


def request_without_redirects(request_fn, *args, **kwargs):
    """Issue a redirect-route request without following the Location.

    httpx eagerly parses the Location header even with following disabled, and
    a spec-valid URL is not always representable by its URL model (e.g. a
    literal ``http://:A`` port). The response never materializes in that case,
    so the example is discarded rather than failed: the service echoed exactly
    what the spec stored, and only the client library cannot exercise it.
    """
    from hypothesis import assume

    kwargs["follow_redirects"] = False
    try:
        return request_fn(*args, **kwargs)
    except httpx.RemoteProtocolError:
        assume(False)
    except httpx.InvalidURL:
        assume(False)


@pytest.fixture(scope="session", autouse=True)
def _admin_endpoint_available():
    """Fail-fast guard: tests need the /admin router reachable with ADMIN_TOKEN.

    Failures here are hard errors (like the Go/TS harnesses), never skips: a
    broken ADMIN_TOKEN setup must not produce a green all-skipped run.
    """
    if INPROC:
        r = client.post("/admin/reset")
    else:
        with httpx.Client(
            base_url=BASE_URL, timeout=5.0, headers=dict(client.headers)
        ) as probe:
            try:
                r = probe.post("/admin/reset")
            except httpx.HTTPError as e:
                pytest.fail(f"service unreachable at {BASE_URL}: {e}")
    if r.status_code == 404:
        pytest.fail(
            "/admin answered 404: the service has no ADMIN_TOKEN configured. "
            "Export ADMIN_TOKEN and restart the service with the same value, "
            "e.g. ADMIN_TOKEN=$(openssl rand -hex 32) docker compose up"
        )
    if r.status_code == 401:
        pytest.fail(
            "/admin rejected the credential (401): ADMIN_TOKEN is missing from "
            "the test environment or differs from the one the service was "
            "started with"
        )
    if r.status_code >= 500:
        pytest.fail(
            f"admin /admin/reset returned {r.status_code}; service is unhealthy"
        )
    if r.status_code != 204:
        pytest.fail(
            f"admin /admin/reset returned {r.status_code}; "
            "the admin contract is not behaving (expected 204)"
        )

def state_snapshot(int_keyed=frozenset()):
    """/admin/state with JSON-stringified keys coerced back per the spec.

    JSON objects stringify every key; relations the spec keys by Int must
    compare and look up by int again or value-to-key invariants like
    `users[user_by_email[e].id]` go quietly false. Only the fields the
    generator names coerce: a digit-looking string key (a short code, say)
    stays a string.
    """
    raw = client.get("/admin/state").json()
    out = {}
    for field, value in raw.items():
        if field in int_keyed and isinstance(value, dict):
            out[field] = {int(k): v for k, v in value.items()}
        else:
            out[field] = value
    return out
