"""Auto-generated by spec-to-rest. Do not edit by hand."""
import atexit
import os
import secrets

import httpx
import pytest

BASE_URL = os.environ.get("SPEC_TEST_BASE_URL", "http://localhost:8000")
INPROC = os.environ.get("SPEC_TEST_INPROC") == "1"
ADMIN_TOKEN = os.environ.get("ADMIN_TOKEN", "")


if INPROC:
    # The token must be in the environment before app.config instantiates
    # Settings, which happens transitively on the app.main import below.
    if not ADMIN_TOKEN:
        ADMIN_TOKEN = secrets.token_hex(32)
        os.environ["ADMIN_TOKEN"] = ADMIN_TOKEN
    from fastapi.testclient import TestClient

    from app.main import app

    client = TestClient(app, base_url=BASE_URL)
    client.__enter__()
    atexit.register(client.__exit__, None, None, None)
else:
    client = httpx.Client(base_url=BASE_URL, timeout=10.0)
    atexit.register(client.close)

if ADMIN_TOKEN:
    client.headers["Authorization"] = f"Bearer {ADMIN_TOKEN}"


@pytest.fixture(scope="session", autouse=True)
def _admin_endpoint_available():
    """Fail-fast guard: tests need the /admin router reachable with ADMIN_TOKEN.

    Failures here are hard errors (like the Go/TS harnesses), never skips: a
    broken ADMIN_TOKEN setup must not produce a green all-skipped run.
    """
    if INPROC:
        r = client.post("/admin/reset")
    else:
        with httpx.Client(
            base_url=BASE_URL, timeout=5.0, headers=dict(client.headers)
        ) as probe:
            try:
                r = probe.post("/admin/reset")
            except httpx.HTTPError as e:
                pytest.fail(f"service unreachable at {BASE_URL}: {e}")
    if r.status_code == 404:
        pytest.fail(
            "/admin answered 404: the service has no ADMIN_TOKEN configured. "
            "Export ADMIN_TOKEN and restart the service with the same value, "
            "e.g. ADMIN_TOKEN=$(openssl rand -hex 32) docker compose up"
        )
    if r.status_code == 401:
        pytest.fail(
            "/admin rejected the credential (401): ADMIN_TOKEN is missing from "
            "the test environment or differs from the one the service was "
            "started with"
        )
    if r.status_code >= 500:
        pytest.fail(
            f"admin /admin/reset returned {r.status_code}; service is unhealthy"
        )
    if r.status_code != 204:
        pytest.fail(
            f"admin /admin/reset returned {r.status_code}; "
            "the admin contract is not behaving (expected 204)"
        )
