"""Spec-recognized predicate helpers. Auto-generated by spec-to-rest --with-tests."""
import datetime
import itertools
import re
from urllib.parse import urlparse


def is_valid_uri(s) -> bool:
    if not isinstance(s, str) or not s:
        return False
    try:
        parsed = urlparse(s)
    except (ValueError, TypeError):
        return False
    return parsed.scheme in ("http", "https") and bool(parsed.netloc)


_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


def is_valid_email(s) -> bool:
    if not isinstance(s, str):
        return False
    return bool(_EMAIL_RE.match(s))


def _powerset(s):
    items = list(s)
    return frozenset(
        frozenset(c)
        for r in range(len(items) + 1)
        for c in itertools.combinations(items, r)
    )
