"""Auto-generated by spec-to-rest --with-tests. Do not edit by hand.

Wrapper for sensitive Hypothesis-generated values. `_RedactedStr` is a `str`
subclass whose `__repr__` masks the value, so failing-example output from
Hypothesis (and pytest argument-formatting) shows `<redacted len=N>`
instead of the raw secret. JSON serialization is unaffected because
`json.dumps` operates on `str.__str__`.
"""
from hypothesis import strategies as st


class _RedactedStr(str):
    __slots__ = ()

    def __repr__(self) -> str:
        return f"<redacted len={len(self)}>"


def redact(strategy: st.SearchStrategy) -> st.SearchStrategy:
    """Wrap a Hypothesis strategy so its values' repr is masked.

    The wrapped strategy still produces real strings (subclasses of str),
    so the value travels over the wire unchanged. Only stringification
    in test output goes through the masked __repr__.
    """
    return strategy.map(_RedactedStr)
