"""Auto-generated by spec-to-rest --with-tests. Do not edit by hand.

Wrapper for sensitive Hypothesis-generated values. `_RedactedStr` is a `str`
subclass whose `__repr__` masks the value, so failing-example output from
Hypothesis (and pytest argument-formatting) shows `<redacted len=N>`
instead of the raw secret. JSON serialization is unaffected because
`json.dumps` operates on `str.__str__`.
"""
from hypothesis import strategies as st


class _RedactedStr(str):
    __slots__ = ()

    def __repr__(self) -> str:
        return f"<redacted len={len(self)}>"


def _wrap(value):
    return _RedactedStr(value) if isinstance(value, str) else value


def redact(strategy: st.SearchStrategy) -> st.SearchStrategy:
    """Wrap a Hypothesis strategy so its values' repr is masked.

    Strings (and str subclasses) become `_RedactedStr` so failing-example
    output shows `<redacted len=N>` instead of the raw value. Non-string
    values (e.g. `None` from `st.one_of(st.none(), ...)`, ints, etc.) pass
    through unchanged — coercing them to `str` would change request
    semantics on the wire.
    """
    return strategy.map(_wrap)
