package specrest.testgen

import specrest.codegen.go.GoLit
import specrest.ir.generated.SpecRestGenerated.*
import specrest.profile.ProfiledService

// Go rendering for the shared NativeBehavioral selection (go test + rapid).
// Selected only for the `chi` target; Python `Behavioral` stays the
// byte-identical oracle.
object GoBehavioral:

  def emitFor(profiled: ProfiledService): BehavioralOutput =
    NativeBehavioral.emitFor(profiled, NativeTarget.Go)(buildPositiveTest)

  private def buildPositiveTest(spec: PositiveTestSpec): GeneratedTest =
    val ok   = spec.pop.endpoint.successStatus
    val call = GoRender.requestCall(spec.pop, identity)
    val viol = GoLit.str(s"ensures violated: ${spec.docstring}")
    val sb   = new StringBuilder
    if spec.arbs.nonEmpty then
      sb.append(s"func ${spec.name}(t *testing.T) {\n")
      sb.append("\tensureAdmin(t)\n")
      sb.append("\trapid.Check(t, func(rt *rapid.T) {\n")
      sb.append("\t\tclient.post(\"/admin/reset\")\n")
      sb.append("\t\tpreState := adminState()\n")
      spec.arbs.foreach: (n, a) =>
        sb.append(s"\t\t$n := ($a).Draw(rt, ${GoLit.str(n)})\n")
        sb.append(s"\t\t_ = $n\n")
      sb.append(s"\t\tresponse := $call\n")
      if spec.nonTrivialRequires then
        sb.append(s"\t\tif response.Status() != $ok {\n\t\t\treturn\n\t\t}\n")
      sb.append(
        s"\t\tif response.Status() != $ok {\n\t\t\trt.Fatalf(\"expected status %d, got %d\", $ok, response.Status())\n\t\t}\n"
      )
      sb.append("\t\tresponseData := response.JSON()\n")
      sb.append("\t\tpostState := adminState()\n")
      sb.append("\t\t_ = preState\n\t\t_ = postState\n\t\t_ = responseData\n")
      sb.append(s"\t\tif !_truthy(${spec.assertion}) {\n\t\t\trt.Fatalf($viol)\n\t\t}\n")
      sb.append("\t})\n")
      sb.append("}\n")
    else
      sb.append(s"func ${spec.name}(t *testing.T) {\n")
      sb.append("\tensureAdmin(t)\n")
      sb.append("\tclient.post(\"/admin/reset\")\n")
      sb.append("\tpreState := adminState()\n")
      sb.append(s"\tresponse := $call\n")
      if spec.nonTrivialRequires then
        sb.append(s"\tif response.Status() != $ok {\n\t\treturn\n\t}\n")
      sb.append(
        s"\tif response.Status() != $ok {\n\t\tt.Fatalf(\"expected status %d, got %d\", $ok, response.Status())\n\t}\n"
      )
      sb.append("\tresponseData := response.JSON()\n")
      sb.append("\tpostState := adminState()\n")
      sb.append("\t_ = preState\n\t_ = postState\n\t_ = responseData\n")
      sb.append(s"\tif !_truthy(${spec.assertion}) {\n\t\tt.Fatalf($viol)\n\t}\n")
      sb.append("}\n")
    GeneratedTest(name = spec.name, body = sb.toString, skipReason = None)

  private def behavioralSkipPlaceholder(ir: ServiceIRFull): String =
    s"""|//go:build conformance
        |
        |// Auto-generated by spec-to-rest. Do not edit by hand.
        |//
        |// No native behavioral test could be built for ${svcName(ir)}: every operation
        |// is a fail-loud stub, has a state-dependent precondition, or references
        |// constructs not assertable black-box. See tests/_testgen_skips.json.
        |
        |package tests
        |
        |import "testing"
        |
        |func Test${GoIdent.sanitize(svcName(ir))}BehavioralAllSkipped(t *testing.T) {
        |\tt.Skip("no behavioral tests generated: every operation is a fail-loud " +
        |\t\t"stub or references untranslatable constructs " +
        |\t\t"(see tests/_testgen_skips.json)")
        |}
        |""".stripMargin

  def renderModule(ir: ServiceIRFull, tests: List[GeneratedTest]): String =
    if tests.isEmpty then behavioralSkipPlaceholder(ir)
    else GoRender.module(tests.map(_.body).mkString("\n"))
