package specrest.testgen

import specrest.codegen.go.GoLit
import specrest.ir.generated.SpecRestGenerated.*
import specrest.profile.ProfiledService

// Go rendering for the shared NativeStateful selection (go test + rapid):
// random operation sequences against the live service, global invariants
// asserted after every step. Python `Stateful` stays the byte-identical
// oracle.
object GoStateful:

  def emitFor(profiled: ProfiledService): StatefulOutput =
    val ir                           = profiled.ir
    val (stepOps, invariants, skips) = NativeStateful.collect(profiled, NativeTarget.Go)
    val file =
      if stepOps.isEmpty || invariants.isEmpty then skipPlaceholder(ir)
      else renderModule(ir, stepOps, invariants)
    StatefulOutput(file = file, skips = skips)

  private def renderModule(
      ir: ServiceIRFull,
      stepOps: List[NativeStepOp],
      invariants: List[(String, String, String)]
  ): String =
    val opNames = stepOps.map(s => GoLit.str(s.name)).mkString(", ")

    val dispatchCases = stepOps
      .map: s =>
        val draws = s.args
          .map((n, a) => s"\t\t\t\t$n := ($a).Draw(rt, ${GoLit.str(n)})\n\t\t\t\t_ = $n")
          .mkString("\n")
        val drawBlock = if s.args.isEmpty then "" else draws + "\n"
        s"\t\t\tcase ${GoLit.str(s.name)}:\n$drawBlock\t\t\t\t${GoRender.requestCall(s.pop, identity)}"
      .mkString("\n")

    val invChecks = invariants
      .map: (name, pretty, text) =>
        val viol = GoLit.str(s"invariant violated: $name ($pretty)")
        s"\t\t\tif !_truthy($text) {\n\t\t\t\trt.Fatalf($viol)\n\t\t\t}"
      .mkString("\n")

    val sb = new StringBuilder
    sb.append(s"func Test${GoIdent.sanitize(svcName(ir))}StatefulInvariants(t *testing.T) {\n")
    sb.append("\tensureAdmin(t)\n")
    sb.append("\trapid.Check(t, func(rt *rapid.T) {\n")
    sb.append("\t\tclient.post(\"/admin/reset\")\n")
    sb.append(
      "\t\tnSteps := int(rapid.Int64Range(1, int64(confStepCount())).Draw(rt, \"steps\"))\n"
    )
    sb.append("\t\tfor i := 0; i < nSteps; i++ {\n")
    sb.append(s"\t\t\top := rapid.SampledFrom([]string{$opNames}).Draw(rt, \"op\")\n")
    sb.append("\t\t\tswitch op {\n")
    sb.append(dispatchCases)
    sb.append("\n\t\t\t}\n")
    sb.append("\t\t\tpostState := adminState()\n")
    sb.append("\t\t\t_ = postState\n")
    sb.append(invChecks)
    sb.append("\n\t\t}\n")
    sb.append("\t})\n")
    sb.append("}\n")
    GoRender.module(sb.toString)

  private def skipPlaceholder(ir: ServiceIRFull): String =
    s"""|//go:build conformance
        |
        |// Auto-generated by spec-to-rest. Do not edit by hand.
        |//
        |// No native stateful test could be built for ${svcName(ir)}: every operation is
        |// a fail-loud stub / has untranslatable inputs, or no global invariant is
        |// black-box assertable. See tests/_testgen_skips.json for the reasons.
        |
        |package tests
        |
        |import "testing"
        |
        |func Test${GoIdent.sanitize(svcName(ir))}StatefulAllSkipped(t *testing.T) {
        |\tt.Skip("no stateful tests generated: every operation is a fail-loud " +
        |\t\t"stub / has untranslatable inputs, or no global invariant is " +
        |\t\t"black-box assertable (see tests/_testgen_skips.json)")
        |}
        |""".stripMargin
