package specrest.testgen

import specrest.codegen.go.GoLit
import specrest.ir.Naming
import specrest.ir.generated.SpecRestGenerated.*
import specrest.profile.ProfiledOperation
import specrest.profile.ProfiledService

// Go rendering for the shared NativeStructural selection (go test + rapid):
// schemathesis's core "documented, no server error" check minus full schema
// validation, reusing the IR `Strategies` seam. Python `Structural` stays the
// byte-identical oracle.
object GoStructural:

  def emitFor(profiled: ProfiledService): BehavioralOutput =
    NativeStructural.emitFor(profiled, NativeTarget.Go)(buildTest)

  private def buildTest(pop: ProfiledOperation, arbs: List[(String, String)]): GeneratedTest =
    val opSnake = Naming.toSnakeCase(pop.operationName)
    val name    = s"Test_structural_$opSnake"
    val ep      = pop.endpoint
    val doc     = s"structural: ${ep.method} ${ep.path} returns no 5xx for schema-valid input"
    val call    = GoRender.requestCall(pop, identity)
    val viol    = GoLit.str(s"server error (5xx) on schema-valid input: $doc")
    val sb      = new StringBuilder
    if arbs.nonEmpty then
      sb.append(s"func $name(t *testing.T) {\n")
      sb.append("\tensureAdmin(t)\n")
      sb.append("\trapid.Check(t, func(rt *rapid.T) {\n")
      sb.append("\t\tclient.post(\"/admin/reset\")\n")
      arbs.foreach: (n, a) =>
        sb.append(s"\t\t$n := ($a).Draw(rt, ${GoLit.str(n)})\n")
        sb.append(s"\t\t_ = $n\n")
      sb.append(s"\t\tresponse := $call\n")
      sb.append(s"\t\tif response.Status() >= 500 {\n\t\t\trt.Fatalf($viol)\n\t\t}\n")
      sb.append("\t})\n")
      sb.append("}\n")
    else
      sb.append(s"func $name(t *testing.T) {\n")
      sb.append("\tensureAdmin(t)\n")
      sb.append("\tclient.post(\"/admin/reset\")\n")
      sb.append(s"\tresponse := $call\n")
      sb.append(s"\tif response.Status() >= 500 {\n\t\tt.Fatalf($viol)\n\t}\n")
      sb.append("}\n")
    GeneratedTest(name = name, body = sb.toString, skipReason = None)

  private def structuralSkipPlaceholder(ir: ServiceIRFull): String =
    s"""|//go:build conformance
        |
        |// Auto-generated by spec-to-rest. Do not edit by hand.
        |//
        |// No native structural test could be built for ${svcName(ir)}: every operation
        |// is a fail-loud stub or has untranslatable inputs. See
        |// tests/_testgen_skips.json (structural_skipped).
        |
        |package tests
        |
        |import "testing"
        |
        |func Test${GoIdent.sanitize(svcName(ir))}StructuralAllSkipped(t *testing.T) {
        |\tt.Skip("no structural tests generated: every operation is a fail-loud " +
        |\t\t"stub or has untranslatable inputs (see tests/_testgen_skips.json)")
        |}
        |""".stripMargin

  def renderModule(ir: ServiceIRFull, tests: List[GeneratedTest]): String =
    if tests.isEmpty then structuralSkipPlaceholder(ir)
    else GoRender.module(tests.map(_.body).mkString("\n"))
