package specrest.testgen

import specrest.convention.Naming
import specrest.ir.generated.SpecRestGenerated.*
import specrest.profile.ProfiledOperation
import specrest.profile.ProfiledService

// Native Go structural-lite (go test + rapid). Reuses the IR `Strategies` seam
// (no OpenAPI/JSON-Schema runtime): for every non-stub operation, generate
// type-valid inputs, call with a per-case reset, assert the server did not 5xx
// — schemathesis's core "documented, no server error" check minus full schema
// validation. Fail-loud stubs are skipped exactly as the Python schemathesis
// renderer excludes them. Python `Structural` stays the byte-identical oracle.
object GoStructural:

  def emitFor(profiled: ProfiledService): BehavioralOutput =
    val ir = profiled.ir
    val collected = profiled.operations.map: pop =>
      if StubOps.isStub(profiled, pop) then
        Left(TestSkip(pop.operationName, "structural", StubOps.skipReason(pop)))
      else
        goInputArbs(pop, ir) match
          case Left(reason) =>
            Left(TestSkip(pop.operationName, "structural", reason))
          case Right(arbs) =>
            Right(buildTest(pop, arbs))
    BehavioralOutput(
      tests = collected.collect { case Right(t) => t },
      skips = collected.collect { case Left(s) => s }
    )

  private def goInputArbs(
      pop: ProfiledOperation,
      ir: ServiceIRFull
  ): Either[String, List[(String, String)]] =
    val ep     = pop.endpoint
    val params = ep.pathParams ++ ep.bodyParams ++ ep.queryParams
    if params.isEmpty then Right(Nil)
    else
      val overrides = TestStrategyOverrides.from(ir)
      val pairs = params.map: p =>
        val sctx = StrategyCtx.OperationInput(pop.operationName, p.name)
        (p.name, Strategies.expressionFor(p.typeExpr, ir, sctx, overrides, GoRapidStrategy))
      pairs.collectFirst { case (n, StrategyExpr.Skip(r)) => s"input '$n': $r" } match
        case Some(reason) => Left(reason)
        case None         => Right(pairs.collect { case (n, StrategyExpr.Code(t)) => (n, t) })

  private def goRequestCall(pop: ProfiledOperation): String =
    val ep = pop.endpoint
    val method = ep.method match
      case _: GET    => "get"
      case _: POST   => "post"
      case _: PUT    => "put"
      case _: PATCH  => "patch"
      case _: DELETE => "delete"
    val pathExpr =
      if ep.pathParams.isEmpty then GoLit.str(ep.path)
      else
        val names = scala.collection.mutable.ListBuffer.empty[String]
        val tmpl = "\\{([^}]+)\\}".r.replaceAllIn(
          ep.path,
          m =>
            names += m.group(1)
            "%v"
        )
        s"fmt.Sprintf(${GoLit.str(tmpl)}, ${names.toList.mkString(", ")})"
    val bodyExpr =
      if ep.bodyParams.isEmpty then ""
      else
        val pairs = ep.bodyParams.map(p => s"${GoLit.str(p.name)}: ${p.name}").mkString(", ")
        s", map[string]any{$pairs}"
    s"client.$method($pathExpr$bodyExpr)"

  private def buildTest(pop: ProfiledOperation, arbs: List[(String, String)]): GeneratedTest =
    val opSnake = Naming.toSnakeCase(pop.operationName)
    val name    = s"Test_structural_$opSnake"
    val ep      = pop.endpoint
    val doc     = s"structural: ${ep.method} ${ep.path} returns no 5xx for schema-valid input"
    val call    = goRequestCall(pop)
    val viol    = GoLit.str(s"server error (5xx) on schema-valid input: $doc")
    val sb      = new StringBuilder
    if arbs.nonEmpty then
      sb.append(s"func $name(t *testing.T) {\n")
      sb.append("\tensureAdmin(t)\n")
      sb.append("\trapid.Check(t, func(rt *rapid.T) {\n")
      sb.append("\t\tclient.post(\"/__test_admin__/reset\")\n")
      arbs.foreach: (n, a) =>
        sb.append(s"\t\t$n := ($a).Draw(rt, ${GoLit.str(n)})\n")
        sb.append(s"\t\t_ = $n\n")
      sb.append(s"\t\tresponse := $call\n")
      sb.append(s"\t\tif response.Status() >= 500 {\n\t\t\trt.Fatalf($viol)\n\t\t}\n")
      sb.append("\t})\n")
      sb.append("}\n")
    else
      sb.append(s"func $name(t *testing.T) {\n")
      sb.append("\tensureAdmin(t)\n")
      sb.append("\tclient.post(\"/__test_admin__/reset\")\n")
      sb.append(s"\tresponse := $call\n")
      sb.append(s"\tif response.Status() >= 500 {\n\t\tt.Fatalf($viol)\n\t}\n")
      sb.append("}\n")
    GeneratedTest(name = name, body = sb.toString, skipReason = None)

  private def goIdent(s: String): String =
    val parts  = s.split("[^A-Za-z0-9]+").filter(_.nonEmpty).map(_.capitalize)
    val joined = parts.mkString
    if joined.isEmpty || !joined.head.isLetter then s"Svc$joined" else joined

  private def structuralSkipPlaceholder(ir: ServiceIRFull): String =
    s"""|//go:build conformance
        |
        |// Auto-generated by spec-to-rest. Do not edit by hand.
        |//
        |// No native structural test could be built for ${svcName(ir)}: every operation
        |// is a fail-loud stub or has untranslatable inputs. See
        |// tests/_testgen_skips.json (structural_skipped).
        |
        |package tests
        |
        |import "testing"
        |
        |func Test${goIdent(svcName(ir))}StructuralAllSkipped(t *testing.T) {
        |\tt.Skip("no structural tests generated: every operation is a fail-loud " +
        |\t\t"stub or has untranslatable inputs (see tests/_testgen_skips.json)")
        |}
        |""".stripMargin

  def renderModule(ir: ServiceIRFull, tests: List[GeneratedTest]): String =
    if tests.isEmpty then structuralSkipPlaceholder(ir)
    else renderFull(tests)

  private def renderFull(tests: List[GeneratedTest]): String =
    val bodies     = tests.map(_.body).mkString("\n")
    val stdlib     = (if bodies.contains("fmt.") then List("\t\"fmt\"") else Nil) :+ "\t\"testing\""
    val thirdParty = if bodies.contains("rapid.") then List("\t\"pgregory.net/rapid\"") else Nil
    val importBlock =
      if thirdParty.isEmpty then stdlib.mkString("\n")
      else stdlib.mkString("\n") + "\n\n" + thirdParty.mkString("\n")
    val sb = new StringBuilder
    sb.append("//go:build conformance\n\n")
    sb.append("// Auto-generated by spec-to-rest. Do not edit by hand.\n\n")
    sb.append("package tests\n\n")
    sb.append(s"import (\n$importBlock\n)\n\n")
    sb.append(bodies)
    sb.toString
