package specrest.testgen

import specrest.codegen.EmittedFile
import specrest.codegen.go.GoLit
import specrest.ir.generated.SpecRestGenerated.ServiceIRFull
import specrest.ir.generated.SpecRestGenerated.expr

object GoTestHarness extends HarnessTemplates:

  private val Root = "testgen-templates/go/chi"

  // Go's toolchain ignores files whose names begin with `_` or `.`, so the
  // TypeScript `_`-prefix convention cannot be reused — these are `conf_*.go`.
  private val RuntimeFile        = "tests/conf_runtime.go"
  private val GenFile            = "tests/conf_gen.go"
  private val ClientFile         = "tests/conf_client.go"
  private val RedactionFile      = "tests/conf_redaction.go"
  private val StrategiesUserFile = "tests/conf_strategies_user.go"
  private val PredicatesFile     = "tests/conf_predicates.go"
  private val MainTestFile       = "tests/conf_main_test.go"
  private val RunConformanceFile = "tests/run_conformance.sh"

  def scaffoldFiles(ir: ServiceIRFull): List[EmittedFile] =
    List(
      EmittedFile(RuntimeFile, TemplateResources.load(Root, RuntimeFile)),
      EmittedFile(GenFile, TemplateResources.load(Root, GenFile)),
      EmittedFile(ClientFile, TemplateResources.load(Root, ClientFile)),
      EmittedFile(RedactionFile, TemplateResources.load(Root, RedactionFile)),
      EmittedFile(
        StrategiesUserFile,
        TemplateResources.load(Root, StrategiesUserFile),
        preserve = true
      ),
      EmittedFile(PredicatesFile, predicates(ir)),
      EmittedFile(MainTestFile, TemplateResources.load(Root, MainTestFile)),
      EmittedFile(RunConformanceFile, TemplateResources.load(Root, RunConformanceFile))
    )

  def strategiesPath: String = "tests/conf_strategies.go"
  def skipsPath: String      = "tests/_testgen_skips.json"

  def behavioralTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}_behavioral_test.go"
  def statefulTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}_stateful_test.go"
  def structuralTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}_structural_test.go"

  private val PredicatesHeader: String =
    """|//go:build conformance
       |
       |// Auto-generated by spec-to-rest. Do not edit by hand.
       |// User-defined functions/predicates translated to Go; values are `any`
       |// since they operate on dynamically-shaped JSON.
       |
       |package tests
       |
       |""".stripMargin

  private def predicates(ir: ServiceIRFull): String =
    val defs = UserDefs.renderAll(ir)((n, ps, b) => renderUserDef(n, ps, b, ir))
    (PredicatesHeader + defs).stripTrailing + "\n"

  private def renderUserDef(
      specName: String,
      paramNames: List[String],
      body: expr,
      ir: ServiceIRFull
  ): String =
    val sigParams    = paramNames.map(p => s"$p any").mkString(", ")
    val nameReserved = GoReservedNames.contains(specName)
    val resParam     = paramNames.find(GoReservedNames.contains)

    def stub(msg: String): String =
      s"func $specName($sigParams) any {\n\tpanic(${GoLit.str(msg)})\n}\n\n"

    if nameReserved then stub(s"testgen: '$specName' is a Go-reserved name")
    else
      resParam match
        case Some(p) =>
          stub(s"testgen: parameter '$p' of '$specName' is a Go-reserved name")
        case None =>
          val ctx = TestCtx.forPredicateBody(paramNames.toSet, ir)
          GoExprBackend.translate(body, ctx) match
            case Translated.Emit(text) =>
              s"func $specName($sigParams) any {\n\treturn $text\n}\n\n"
            case Translated.Skip(reason, _) =>
              stub(s"testgen: cannot translate body of '$specName': $reason")
