package specrest.testgen

import specrest.codegen.EmittedFile
import specrest.ir.generated.SpecRestGenerated.EnumDeclFull
import specrest.ir.generated.SpecRestGenerated.FunctionDeclFull
import specrest.ir.generated.SpecRestGenerated.ParamDeclFull
import specrest.ir.generated.SpecRestGenerated.PredicateDeclFull
import specrest.ir.generated.SpecRestGenerated.ServiceIRFull
import specrest.ir.generated.SpecRestGenerated.expr_full

import java.io.ByteArrayOutputStream
import java.nio.charset.StandardCharsets

@SuppressWarnings(Array("org.wartremover.warts.Var", "org.wartremover.warts.Null"))
object GoTestHarness extends HarnessTemplates:

  private val Root = "testgen-templates/go/chi"

  // Go's toolchain ignores files whose names begin with `_` or `.`, so the
  // TypeScript `_`-prefix convention cannot be reused — these are `conf_*.go`.
  private val RuntimeFile        = "tests/conf_runtime.go"
  private val GenFile            = "tests/conf_gen.go"
  private val ClientFile         = "tests/conf_client.go"
  private val RedactionFile      = "tests/conf_redaction.go"
  private val StrategiesUserFile = "tests/conf_strategies_user.go"
  private val PredicatesFile     = "tests/conf_predicates.go"
  private val MainTestFile       = "tests/conf_main_test.go"
  private val RunConformanceFile = "tests/run_conformance.sh"

  def scaffoldFiles(ir: ServiceIRFull): List[EmittedFile] =
    List(
      EmittedFile(RuntimeFile, loadResource(RuntimeFile)),
      EmittedFile(GenFile, loadResource(GenFile)),
      EmittedFile(ClientFile, loadResource(ClientFile)),
      EmittedFile(RedactionFile, loadResource(RedactionFile)),
      EmittedFile(StrategiesUserFile, loadResource(StrategiesUserFile)),
      EmittedFile(PredicatesFile, predicates(ir)),
      EmittedFile(MainTestFile, loadResource(MainTestFile)),
      EmittedFile(RunConformanceFile, loadResource(RunConformanceFile))
    )

  def strategiesPath: String = "tests/conf_strategies.go"
  def skipsPath: String      = "tests/_testgen_skips.json"

  def behavioralTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}_behavioral_test.go"
  def statefulTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}_stateful_test.go"
  def structuralTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}_structural_test.go"

  private val PredicatesHeader: String =
    """|//go:build conformance
       |
       |// Auto-generated by spec-to-rest --with-tests. Do not edit by hand.
       |// User-defined functions/predicates translated to Go; values are `any`
       |// since they operate on dynamically-shaped JSON.
       |
       |package tests
       |
       |""".stripMargin

  private def predicates(ir: ServiceIRFull): String =
    PredicatesHeader + renderUserDefinitions(ir)

  private def renderUserDefinitions(ir: ServiceIRFull): String =
    val parts = ir.l.collect { case _f: FunctionDeclFull => renderFunction(_f, ir) } ++
      ir.m.collect { case _p: PredicateDeclFull => renderPredicate(_p, ir) }
    parts.mkString("")

  private def renderFunction(fn: FunctionDeclFull, ir: ServiceIRFull): String =
    renderUserDef(fn.a, fn.b.collect { case ParamDeclFull(_n, _, _) => _n }, fn.d, ir)

  private def renderPredicate(pr: PredicateDeclFull, ir: ServiceIRFull): String =
    renderUserDef(pr.a, pr.b.collect { case ParamDeclFull(_n, _, _) => _n }, pr.c, ir)

  private def renderUserDef(
      specName: String,
      paramNames: List[String],
      body: expr_full,
      ir: ServiceIRFull
  ): String =
    val sigParams    = paramNames.map(p => s"$p any").mkString(", ")
    val nameReserved = GoReservedNames.contains(specName)
    val resParam     = paramNames.find(GoReservedNames.contains)

    def stub(msg: String): String =
      s"func $specName($sigParams) any {\n\tpanic(${GoLit.str(msg)})\n}\n\n"

    if nameReserved then stub(s"testgen: '$specName' is a Go-reserved name")
    else
      resParam match
        case Some(p) =>
          stub(s"testgen: parameter '$p' of '$specName' is a Go-reserved name")
        case None =>
          val ctx = predicateBodyCtx(paramNames.toSet, ir)
          GoExprBackend.translate(body, ctx) match
            case ExprPy.Py(text) =>
              s"func $specName($sigParams) any {\n\treturn $text\n}\n\n"
            case ExprPy.Skip(reason, _) =>
              stub(s"testgen: cannot translate body of '$specName': $reason")

  private def predicateBodyCtx(params: Set[String], ir: ServiceIRFull): TestCtx =
    TestCtx(
      inputs = params,
      outputs = Set.empty,
      stateFields = Set.empty,
      mapStateFields = Set.empty,
      enumValues = ir.d.collect { case e: EnumDeclFull => e.a -> e.b.toSet }.toMap,
      userFunctions = ir.l.collect { case f: FunctionDeclFull => f.a -> f }.toMap,
      userPredicates = ir.m.collect { case p: PredicateDeclFull => p.a -> p }.toMap,
      boundVars = Set.empty,
      capture = CaptureMode.PostState
    )

  private def loadResource(relPath: String): String =
    val resourcePath = s"$Root/$relPath"
    val is           = getClass.getClassLoader.getResourceAsStream(resourcePath)
    if is eq null then
      throw new RuntimeException(s"testgen template resource missing: $resourcePath")
    try
      val out    = new ByteArrayOutputStream()
      val buffer = new Array[Byte](8192)
      var read   = is.read(buffer)
      while read != -1 do
        out.write(buffer, 0, read)
        read = is.read(buffer)
      new String(out.toByteArray, StandardCharsets.UTF_8)
    finally is.close()
