package specrest.testgen

import specrest.codegen.EmittedFile
import specrest.convention.Naming
import specrest.ir.generated.SpecRestGenerated.svcName
import specrest.profile.ProfiledService

object TestEmit:

  def emit(profiled: ProfiledService): List[EmittedFile] =
    if profiled.profile.framework == "express" then emitTs(profiled)
    else if profiled.profile.framework == "chi" then emitGo(profiled)
    else emitPython(profiled)

  // Native Go conformance (go test + rapid). Structural fuzzing is not yet
  // ported (#175) — honest-skipped; structural invariants are exercised by the
  // stateful suite. Behavioral/stateful are the Go emitters; the spec-derived
  // test-admin router is build-tagged `conformance` (the codegen side emits the
  // always-present `!conformance` no-op stub + main.go wiring).
  private def emitGo(profiled: ProfiledService): List[EmittedFile] =
    val ir            = profiled.ir
    val serviceSnake  = Naming.toSnakeCase(svcName(ir))
    val harness       = GoTestHarness
    val stratSpecs    = Strategies.forIR(ir, GoRapidStrategy)
    val behavioralOut = GoBehavioral.emitFor(profiled)
    val statefulOut   = GoStateful.emitFor(profiled)
    val structuralOut = GoStructural.emitFor(profiled)
    val skipsJson = renderSkipsJson(
      svcName(ir),
      stratSpecs,
      behavioralOut.skips ++ statefulOut.skips,
      structuralOut.skips
    )
    EmittedFile(FilePaths.AdminRouterFileGo, AdminRouterGo.emit(profiled)) ::
      harness.scaffoldFiles(ir) ++
      List(
        EmittedFile(harness.strategiesPath, renderGoStrategiesFile(stratSpecs)),
        EmittedFile(
          harness.behavioralTestPath(serviceSnake),
          GoBehavioral.renderModule(ir, behavioralOut.tests)
        ),
        EmittedFile(harness.statefulTestPath(serviceSnake), statefulOut.file),
        EmittedFile(
          harness.structuralTestPath(serviceSnake),
          GoStructural.renderModule(ir, structuralOut.tests)
        ),
        EmittedFile(harness.skipsPath, skipsJson)
      )

  private def renderGoStrategiesFile(specs: List[StrategySpec]): String =
    val sb = new StringBuilder
    sb.append("//go:build conformance\n\n")
    sb.append("// Auto-generated by spec-to-rest. Do not edit by hand.\n\n")
    sb.append("package tests\n\n")
    if specs.isEmpty then
      sb.append("// No strategies generated for this service.\n")
    else
      sb.append("import \"pgregory.net/rapid\"\n\n")
      specs.foreach: spec =>
        spec.skipped.foreach(s => sb.append(s"// testgen-skip: $s\n"))
        sb.append(s"func ${spec.functionName}() *rapid.Generator[any] {\n")
        sb.append(s"\treturn ${spec.body}\n}\n\n")
    sb.toString

  // Native TypeScript conformance (vitest + fast-check). Structural fuzzing is
  // not yet ported (#175) — it is honest-skipped; structural invariants are
  // exercised by the stateful suite. Behavioral/stateful are the TS emitters.
  private def emitTs(profiled: ProfiledService): List[EmittedFile] =
    val ir            = profiled.ir
    val serviceSnake  = Naming.toSnakeCase(svcName(ir))
    val harness       = TsVitestHarness
    val stratSpecs    = Strategies.forIR(ir, TsFastCheckStrategy)
    val behavioralOut = TsBehavioral.emitFor(profiled)
    val statefulOut   = TsStateful.emitFor(profiled)
    val structuralOut = TsStructural.emitFor(profiled)
    val skipsJson = renderSkipsJson(
      svcName(ir),
      stratSpecs,
      behavioralOut.skips ++ statefulOut.skips,
      structuralOut.skips
    )
    EmittedFile(FilePaths.AdminRouterFileTs, AdminRouterTs.emit(profiled)) ::
      harness.scaffoldFiles(ir) ++
      List(
        EmittedFile(harness.strategiesPath, renderTsStrategiesFile(stratSpecs)),
        EmittedFile(
          harness.behavioralTestPath(serviceSnake),
          TsBehavioral.renderModule(ir, behavioralOut.tests)
        ),
        EmittedFile(harness.statefulTestPath(serviceSnake), statefulOut.file),
        EmittedFile(
          harness.structuralTestPath(serviceSnake),
          TsStructural.renderModule(ir, structuralOut.tests)
        ),
        EmittedFile(harness.skipsPath, skipsJson)
      )

  private def renderTsStrategiesFile(specs: List[StrategySpec]): String =
    val bodies = specs.map(_.body).mkString
    val usesRedact =
      bodies.contains("redact(") || specs.exists(_.body.contains("\"***REDACTED***\""))
    val rtHelpers =
      List("_diff", "_eq", "_in", "_inter", "_len", "_powerset", "_sha256Hex", "_subset", "_union")
        .filter(h => bodies.contains(s"$h("))
    val userImports = specs
      .flatMap(_.imports)
      .distinct
      .groupBy(_.module)
      .toList
      .sortBy(_._1)
      .map((module, imps) =>
        s"import { ${imps.map(_.symbol).distinct.sorted.mkString(", ")} } from \"$module\";"
      )
    val sb = new StringBuilder
    sb.append("// Auto-generated by spec-to-rest. Do not edit by hand.\n")
    sb.append("/* eslint-disable @typescript-eslint/no-explicit-any */\n")
    sb.append("import fc from \"fast-check\";\n")
    if usesRedact then sb.append("import { redact } from \"./_redaction.js\";\n")
    if rtHelpers.nonEmpty then
      sb.append(s"import { ${rtHelpers.mkString(", ")} } from \"./_runtime.js\";\n")
    userImports.foreach(i => sb.append(i + "\n"))
    sb.append("\n")
    if specs.isEmpty then sb.append("// No strategies generated for this service.\n")
    else
      specs.foreach: spec =>
        spec.skipped.foreach(s => sb.append(s"// testgen-skip: $s\n"))
        sb.append(s"export function ${spec.functionName}(): fc.Arbitrary<any> {\n")
        sb.append(s"  return ${spec.body};\n}\n\n")
    sb.toString

  private def emitPython(profiled: ProfiledService): List[EmittedFile] =
    val ir            = profiled.ir
    val serviceSnake  = Naming.toSnakeCase(svcName(ir))
    val harness       = TestBackend.harnessFor(profiled)
    val strategySpecs = Strategies.forIR(ir)
    val behavioralOut = Behavioral.emitFor(profiled)
    val statefulOut   = Stateful.emitFor(profiled)
    val structuralOut = Structural.emitFor(profiled)
    // The conformance bundle (conftest/run_conformance/behavioral/stateful/structural) is the
    // spec-derived, language-agnostic HTTP black-box suite — emitted identically for every
    // target. Only the test-admin router is language-specific.
    val (adminRouterFile, adminRouterSrc) =
      if profiled.profile.framework == "express" then
        (FilePaths.AdminRouterFileTs, AdminRouterTs.emit(profiled))
      else (FilePaths.AdminRouterFile, AdminRouter.emit(profiled))
    val strategiesPy = renderStrategiesFile(strategySpecs)
    val behavioralPy = renderBehavioralFile(behavioralOut.tests, svcName(ir), strategySpecs)
    val skipsJson =
      renderSkipsJson(
        svcName(ir),
        strategySpecs,
        behavioralOut.skips ++ statefulOut.skips,
        structuralOut.skips
      )

    EmittedFile(adminRouterFile, adminRouterSrc) ::
      harness.scaffoldFiles(ir) ++
      List(
        EmittedFile(harness.strategiesPath, strategiesPy),
        EmittedFile(harness.behavioralTestPath(serviceSnake), behavioralPy),
        EmittedFile(harness.statefulTestPath(serviceSnake), statefulOut.file),
        EmittedFile(harness.structuralTestPath(serviceSnake), structuralOut.file),
        EmittedFile(harness.skipsPath, skipsJson)
      )

  private def renderStrategiesFile(specs: List[StrategySpec]): String =
    val baseHeader =
      """|\"\"\"Auto-generated Hypothesis strategies. Do not edit by hand.\"\"\"
         |from hypothesis import strategies as st
         |
         |from tests.predicates import is_valid_email, is_valid_uri
         |""".stripMargin.replace("\\\"", "\"")

    val userImports = specs.flatMap(_.imports).distinct
    val userImportsBlock =
      userImports
        .groupBy(_.module)
        .toList
        .sortBy(_._1)
        .map: (module, imps) =>
          val syms = imps.map(_.symbol).distinct.sorted.mkString(", ")
          s"from $module import $syms"
        .mkString("\n")

    val header =
      if userImportsBlock.isEmpty then baseHeader + "\n"
      else baseHeader + userImportsBlock + "\n\n"

    if specs.isEmpty then header + "# No strategies generated for this service.\n"
    else
      val funcs = specs
        .map: spec =>
          val skipNote =
            if spec.skipped.isEmpty then ""
            else
              spec.skipped.map(s => s"# testgen-skip: $s").mkString("", "\n", "\n")
          s"${skipNote}def ${spec.functionName}():\n    return ${spec.body}\n"
        .mkString("\n")
      header + funcs

  private def renderBehavioralFile(
      tests: List[GeneratedTest],
      serviceName: String,
      strategies: List[StrategySpec]
  ): String =
    val strategyImport =
      if strategies.isEmpty then ""
      else
        val names = strategies.map(_.functionName).sorted.mkString(",\n    ")
        s"""|from tests.strategies import (
            |    $names,
            |)
            |
            |""".stripMargin

    val header =
      s"""|\"\"\"Auto-generated behavioral tests for $serviceName.
         |
         |Each ensures clause that ExprToPython could translate produces a positive
         |property test. Each `<input> in <state>` requires clause produces a
         |negative test asserting the missing-key path returns 4xx. Each global
         |invariant produces a post-operation check. See tests/_testgen_skips.json
         |for clauses that were not turned into tests.
         |\"\"\"
         |import datetime
         |import hashlib
         |import re
         |
         |from hypothesis import HealthCheck, assume, given, settings
         |from hypothesis import strategies as st
         |
         |from tests.conftest import client
         |from tests.predicates import is_valid_email, is_valid_uri
         |from tests.redaction import redact
         |
         |""".stripMargin.replace("\\\"", "\"")

    // A module with zero tests makes pytest exit 5 ("no tests collected") — a hard
    // failure. When every operation is a fail-loud stub or untranslatable, emit one
    // explicit skip so the phase passes honestly; reasons live in _testgen_skips.json.
    if tests.isEmpty then
      s"""|\"\"\"Auto-generated behavioral tests for $serviceName.
          |
          |No behavioral property tests could be generated: every operation is a
          |fail-loud stub or references constructs that cannot be asserted
          |black-box. See tests/_testgen_skips.json for the per-clause reasons.
          |\"\"\"
          |import pytest
          |
          |
          |def test_behavioral_all_skipped():
          |    pytest.skip(
          |        "no behavioral tests generated: every operation is a fail-loud "
          |        "stub or references untranslatable constructs "
          |        "(see tests/_testgen_skips.json)"
          |    )
          |""".stripMargin.replace("\\\"", "\"")
    else header + strategyImport + tests.map(_.body).mkString("\n\n")

  private def renderSkipsJson(
      serviceName: String,
      strategies: List[StrategySpec],
      behavioralSkips: List[TestSkip],
      structuralSkips: List[TestSkip]
  ): String =
    val strategyEntries = strategies.flatMap: spec =>
      spec.skipped.map(reason =>
        s"""|    {"type": ${jsonString(spec.typeName)}, "reason": ${jsonString(reason)}}"""
      )
    val skipEntry = (s: TestSkip) =>
      s"""|    {"operation": ${jsonString(s.operation)}, "kind": ${jsonString(
          s.kind
        )}, "reason": ${jsonString(s.reason)}}"""
    val behavioralEntries = behavioralSkips.map(skipEntry)
    val structuralEntries = structuralSkips.map(skipEntry)

    val strategiesArr = renderJsonArray(strategyEntries)
    val behavioralArr = renderJsonArray(behavioralEntries)
    val structuralArr = renderJsonArray(structuralEntries)
    s"""|{
        |  "version": 1,
        |  "service": ${jsonString(serviceName)},
        |  "strategies_skipped": $strategiesArr,
        |  "behavioral_skipped": $behavioralArr,
        |  "structural_skipped": $structuralArr
        |}
        |""".stripMargin

  private def renderJsonArray(entries: List[String]): String =
    if entries.isEmpty then "[]"
    else entries.mkString("[\n", ",\n", "\n  ]")

  private def jsonString(s: String): String =
    val sb = new StringBuilder
    sb.append('"')
    s.foreach:
      case '"'                  => sb.append("\\\"")
      case '\\'                 => sb.append("\\\\")
      case '\n'                 => sb.append("\\n")
      case '\r'                 => sb.append("\\r")
      case '\t'                 => sb.append("\\t")
      case c if c < 0x20.toChar => sb.append(f"\\u${c.toInt}%04x")
      case c                    => sb.append(c)
    sb.append('"')
    sb.toString
