package specrest.testgen

import specrest.ir.generated.SpecRestGenerated.*
import specrest.profile.ProfiledService

// TypeScript rendering for the shared NativeBehavioral selection (vitest +
// fast-check). Selected only for the `express` target; Python `Behavioral`
// stays the byte-identical oracle.
object TsBehavioral:

  def emitFor(profiled: ProfiledService): BehavioralOutput =
    NativeBehavioral.emitFor(profiled, NativeTarget.Ts)(buildPositiveTest)

  private def buildPositiveTest(spec: PositiveTestSpec): GeneratedTest =
    val ok   = spec.pop.endpoint.successStatus
    val call = TsRender.requestCall(spec.pop, identity)
    val viol = TsLit.str(s"ensures violated: ${spec.docstring}")
    val sb   = new StringBuilder
    if spec.arbs.nonEmpty then
      val arbList   = spec.arbs.map(_._2).mkString(", ")
      val paramList = spec.arbs.map(_._1).mkString(", ")
      sb.append(s"test(${TsLit.str(spec.name)}, async () => {\n")
      sb.append("  await fc.assert(\n")
      sb.append(s"    fc.asyncProperty($arbList, async ($paramList) => {\n")
      sb.append("      await client.post(\"/admin/reset\");\n")
      sb.append(
        "      const preState = (await (await client.get(\"/admin/state\"))" +
          ".json()) as any;\n"
      )
      sb.append(s"      const response = await $call;\n")
      if spec.nonTrivialRequires then sb.append(s"      fc.pre(response.status === $ok);\n")
      sb.append(s"      expect(response.status).toBe($ok);\n")
      sb.append("      const responseData = (await response.json()) as any;\n")
      sb.append(
        "      const postState = (await (await client.get(\"/admin/state\"))" +
          ".json()) as any;\n"
      )
      sb.append(s"      if (!(${spec.assertion})) { throw new Error($viol); }\n")
      sb.append("    }),\n")
      sb.append("    { numRuns: NUM_RUNS },\n")
      sb.append("  );\n")
      sb.append("});\n")
    else
      sb.append(s"test(${TsLit.str(spec.name)}, async () => {\n")
      sb.append("  await client.post(\"/admin/reset\");\n")
      sb.append(
        "  const preState = (await (await client.get(\"/admin/state\"))" +
          ".json()) as any;\n"
      )
      sb.append(s"  const response = await $call;\n")
      if spec.nonTrivialRequires then
        sb.append(s"  if (response.status !== $ok) { return; }\n")
      sb.append(s"  expect(response.status).toBe($ok);\n")
      sb.append("  const responseData = (await response.json()) as any;\n")
      sb.append(
        "  const postState = (await (await client.get(\"/admin/state\"))" +
          ".json()) as any;\n"
      )
      sb.append(s"  if (!(${spec.assertion})) { throw new Error($viol); }\n")
      sb.append("});\n")
    GeneratedTest(name = spec.name, body = sb.toString, skipReason = None)

  // vitest fails a test file that contains zero tests (the same hazard as
  // pytest exit-5). When every behavioral op is a fail-loud stub / state-dep /
  // untranslatable, emit one honest skip; reasons are in _testgen_skips.json.
  private def behavioralSkipPlaceholder(ir: ServiceIRFull): String =
    s"""|// Auto-generated by spec-to-rest. Do not edit by hand.
        |//
        |// No native behavioral test could be built for ${svcName(ir)}: every operation
        |// is a fail-loud stub, has a state-dependent precondition, or references
        |// constructs not assertable black-box. See tests/_testgen_skips.json.
        |import { test } from "vitest";
        |
        |test.skip("${svcName(
         ir
       )} behavioral: no assertable ensures (see _testgen_skips.json)", () => {});
        |""".stripMargin

  def renderModule(ir: ServiceIRFull, tests: List[GeneratedTest]): String =
    if tests.isEmpty then behavioralSkipPlaceholder(ir)
    else renderFull(ir, tests)

  private def renderFull(ir: ServiceIRFull, tests: List[GeneratedTest]): String =
    val bodies = tests.map(_.body).mkString("\n")
    val sb     = new StringBuilder
    sb.append(TsRender.Header)
    sb.append("import { expect, test } from \"vitest\";\n")
    sb.append("import fc from \"fast-check\";\n")
    sb.append("import { client } from \"./_client.js\";\n")
    TsRender.runtimeImport(bodies).foreach(sb.append)
    TsRender.predicatesImport(ir, bodies).foreach(sb.append)
    TsRender.strategiesImport(ir, bodies).foreach(sb.append)
    sb.append("\n")
    sb.append(TsRender.NumRunsPreamble)
    sb.append(bodies)
    sb.toString
