package specrest.testgen

import specrest.convention.Naming
import specrest.ir.generated.SpecRestGenerated.ServiceIRFull
import specrest.profile.ProfiledOperation
import specrest.profile.ProfiledService

// Native TypeScript structural-lite (vitest + fast-check). schemathesis has no
// TS peer; rather than reimplement an OpenAPI/JSON-Schema fuzzer we reuse the
// IR `Strategies` seam: for every non-stub operation, generate type-valid
// inputs, call with a per-case reset, and assert the server did not 5xx
// (schemathesis's core "documented, no server error" check, minus full schema
// validation). Fail-loud stubs are skipped exactly as the Python schemathesis
// renderer excludes them. Python `Structural` stays the byte-identical oracle.
object TsStructural:

  def emitFor(profiled: ProfiledService): BehavioralOutput =
    val ir = profiled.ir
    val collected = profiled.operations.map: pop =>
      if StubOps.isStub(profiled, pop) then
        Left(TestSkip(pop.operationName, "structural", StubOps.skipReason(pop)))
      else
        tsInputArbs(pop, ir) match
          case Left(reason) =>
            Left(TestSkip(pop.operationName, "structural", reason))
          case Right(arbs) =>
            Right(buildTest(pop, arbs))
    BehavioralOutput(
      tests = collected.collect { case Right(t) => t },
      skips = collected.collect { case Left(s) => s }
    )

  private def tsInputArbs(
      pop: ProfiledOperation,
      ir: ServiceIRFull
  ): Either[String, List[(String, String)]] =
    val ep     = pop.endpoint
    val params = ep.pathParams ++ ep.bodyParams ++ ep.queryParams
    if params.isEmpty then Right(Nil)
    else
      val overrides = TestStrategyOverrides.from(ir)
      val pairs = params.map: p =>
        val sctx = StrategyCtx.OperationInput(pop.operationName, p.name)
        (p.name, Strategies.expressionFor(p.typeExpr, ir, sctx, overrides, TsFastCheckStrategy))
      pairs.collectFirst { case (n, StrategyExpr.Skip(r)) => s"input '$n': $r" } match
        case Some(reason) => Left(reason)
        case None         => Right(pairs.collect { case (n, StrategyExpr.Code(t)) => (n, t) })

  private def tsRequestCall(pop: ProfiledOperation): String =
    val ep      = pop.endpoint
    val method  = ep.method.toString.toLowerCase
    val hasPath = ep.pathParams.nonEmpty
    val rawPath = ep.path.replaceAll("\\{([^}]+)\\}", "\\$\\{$1\\}")
    val pathExpr =
      if hasPath then s"`$rawPath`" else TsLit.str(ep.path)
    val bodyExpr =
      if ep.bodyParams.isEmpty then ""
      else
        val pairs = ep.bodyParams.map(p => s"${TsLit.str(p.name)}: ${p.name}").mkString(", ")
        s", { $pairs }"
    s"client.$method($pathExpr$bodyExpr)"

  private def buildTest(pop: ProfiledOperation, arbs: List[(String, String)]): GeneratedTest =
    val opSnake = Naming.toSnakeCase(pop.operationName)
    val name    = s"test_structural_$opSnake"
    val ep      = pop.endpoint
    val doc     = s"structural: ${ep.method} ${ep.path} returns no 5xx for schema-valid input"
    val call    = tsRequestCall(pop)
    val viol    = TsLit.str(s"server error (5xx) on schema-valid input: $doc")
    val sb      = new StringBuilder
    if arbs.nonEmpty then
      val arbList   = arbs.map(_._2).mkString(", ")
      val paramList = arbs.map(_._1).mkString(", ")
      sb.append(s"test(${TsLit.str(name)}, async () => {\n")
      sb.append("  await fc.assert(\n")
      sb.append(s"    fc.asyncProperty($arbList, async ($paramList) => {\n")
      sb.append("      await client.post(\"/__test_admin__/reset\");\n")
      sb.append(s"      const response = await $call;\n")
      sb.append(s"      if (response.status >= 500) { throw new Error($viol); }\n")
      sb.append("    }),\n")
      sb.append("    { numRuns: NUM_RUNS },\n")
      sb.append("  );\n")
      sb.append("});\n")
    else
      sb.append(s"test(${TsLit.str(name)}, async () => {\n")
      sb.append("  await client.post(\"/__test_admin__/reset\");\n")
      sb.append(s"  const response = await $call;\n")
      sb.append(s"  if (response.status >= 500) { throw new Error($viol); }\n")
      sb.append("});\n")
    GeneratedTest(name = name, body = sb.toString, skipReason = None)

  private def structuralSkipPlaceholder(ir: ServiceIRFull): String =
    s"""|// Auto-generated by spec-to-rest. Do not edit by hand.
        |//
        |// No native structural test could be built for ${ir.a}: every operation
        |// is a fail-loud stub or has untranslatable inputs. See
        |// tests/_testgen_skips.json (structural_skipped).
        |import { test } from "vitest";
        |
        |test.skip("${ir.a} structural: no fuzzable operations (see _testgen_skips.json)", () => {});
        |""".stripMargin

  def renderModule(ir: ServiceIRFull, tests: List[GeneratedTest]): String =
    if tests.isEmpty then structuralSkipPlaceholder(ir)
    else renderFull(ir, tests)

  private def renderFull(ir: ServiceIRFull, tests: List[GeneratedTest]): String =
    val bodies = tests.map(_.body).mkString("\n")
    val stratNames =
      Strategies.forIR(ir, TsFastCheckStrategy).map(_.functionName).distinct.sorted
        .filter(n => bodies.contains(s"$n("))
    val sb = new StringBuilder
    sb.append("// Auto-generated by spec-to-rest. Do not edit by hand.\n")
    sb.append("/* eslint-disable @typescript-eslint/no-explicit-any */\n")
    sb.append("import { test } from \"vitest\";\n")
    sb.append("import fc from \"fast-check\";\n")
    sb.append("import { client } from \"./_client.js\";\n")
    if stratNames.nonEmpty then
      sb.append(s"import { ${stratNames.mkString(", ")} } from \"./_strategies.js\";\n")
    sb.append("\n")
    sb.append("const _RUNS: Record<string, number> = ")
    sb.append("{ smoke: 20, thorough: 100, exhaustive: 500 };\n")
    sb.append(
      "const NUM_RUNS = _RUNS[process.env.SPEC_TEST_PROFILE ?? \"thorough\"] ?? 100;\n\n"
    )
    sb.append(bodies)
    sb.toString
