package specrest.testgen

import specrest.ir.Naming
import specrest.ir.generated.SpecRestGenerated.*
import specrest.profile.ProfiledOperation
import specrest.profile.ProfiledService

// TypeScript rendering for the shared NativeStructural selection (vitest +
// fast-check). schemathesis has no TS peer; rather than reimplement an
// OpenAPI/JSON-Schema fuzzer we reuse the IR `Strategies` seam for its core
// "documented, no server error" check. Python `Structural` stays the
// byte-identical oracle.
object TsStructural:

  def emitFor(profiled: ProfiledService): BehavioralOutput =
    NativeStructural.emitFor(profiled, NativeTarget.Ts)(buildTest)

  private def buildTest(pop: ProfiledOperation, arbs: List[(String, String)]): GeneratedTest =
    val opSnake = Naming.toSnakeCase(pop.operationName)
    val name    = s"test_structural_$opSnake"
    val ep      = pop.endpoint
    val doc     = s"structural: ${ep.method} ${ep.path} returns no 5xx for schema-valid input"
    val call    = TsRender.requestCall(pop, identity)
    val viol    = TsLit.str(s"server error (5xx) on schema-valid input: $doc")
    val sb      = new StringBuilder
    if arbs.nonEmpty then
      val arbList   = arbs.map(_._2).mkString(", ")
      val paramList = arbs.map(_._1).mkString(", ")
      sb.append(s"test(${TsLit.str(name)}, async () => {\n")
      sb.append("  await fc.assert(\n")
      sb.append(s"    fc.asyncProperty($arbList, async ($paramList) => {\n")
      sb.append("      await client.post(\"/admin/reset\");\n")
      sb.append(s"      const response = await $call;\n")
      sb.append(s"      if (response.status >= 500) { throw new Error($viol); }\n")
      sb.append("    }),\n")
      sb.append("    { numRuns: NUM_RUNS },\n")
      sb.append("  );\n")
      sb.append("});\n")
    else
      sb.append(s"test(${TsLit.str(name)}, async () => {\n")
      sb.append("  await client.post(\"/admin/reset\");\n")
      sb.append(s"  const response = await $call;\n")
      sb.append(s"  if (response.status >= 500) { throw new Error($viol); }\n")
      sb.append("});\n")
    GeneratedTest(name = name, body = sb.toString, skipReason = None)

  private def structuralSkipPlaceholder(ir: ServiceIRFull): String =
    s"""|// Auto-generated by spec-to-rest. Do not edit by hand.
        |//
        |// No native structural test could be built for ${svcName(ir)}: every operation
        |// is a fail-loud stub or has untranslatable inputs. See
        |// tests/_testgen_skips.json (structural_skipped).
        |import { test } from "vitest";
        |
        |test.skip("${svcName(
         ir
       )} structural: no fuzzable operations (see _testgen_skips.json)", () => {});
        |""".stripMargin

  def renderModule(ir: ServiceIRFull, tests: List[GeneratedTest]): String =
    if tests.isEmpty then structuralSkipPlaceholder(ir)
    else renderFull(ir, tests)

  private def renderFull(ir: ServiceIRFull, tests: List[GeneratedTest]): String =
    val bodies = tests.map(_.body).mkString("\n")
    val sb     = new StringBuilder
    sb.append(TsRender.Header)
    sb.append("import { test } from \"vitest\";\n")
    sb.append("import fc from \"fast-check\";\n")
    sb.append("import { client } from \"./_client.js\";\n")
    TsRender.strategiesImport(ir, bodies).foreach(sb.append)
    sb.append("\n")
    sb.append(TsRender.NumRunsPreamble)
    sb.append(bodies)
    sb.toString
