package specrest.testgen

import specrest.ir.generated.SpecRestGenerated.*
import specrest.profile.ProfiledService

// TypeScript rendering for the shared NativeStateful selection (vitest +
// fast-check): random operation sequences against the live service, global
// invariants asserted after every step. Python `Stateful` stays the
// byte-identical oracle.
object TsStateful:

  def emitFor(profiled: ProfiledService): StatefulOutput =
    val ir                           = profiled.ir
    val (stepOps, invariants, skips) = NativeStateful.collect(profiled, NativeTarget.Ts)
    val file =
      if stepOps.isEmpty || invariants.isEmpty then skipPlaceholder(ir)
      else renderModule(ir, stepOps, invariants)
    StatefulOutput(file = file, skips = skips)

  private def renderModule(
      ir: ServiceIRFull,
      stepOps: List[NativeStepOp],
      invariants: List[(String, String, String)]
  ): String =
    val stepArbs = stepOps
      .map: s =>
        val fields = (("op", s"fc.constant(${TsLit.str(s.name)})")
          :: s.args.map((n, a) => (n, a)))
          .map((k, v) => s"$k: $v")
          .mkString(", ")
        s"    fc.record({ $fields })"
      .mkString(",\n")

    val dispatchCases = stepOps
      .map: s =>
        s"    case ${TsLit.str(s.name)}: { await ${TsRender.requestCall(s.pop, n => s"step.$n")}; return; }"
      .mkString("\n")

    val invChecks = invariants
      .map: (name, pretty, text) =>
        val viol = TsLit.str(s"invariant violated: $name ($pretty)")
        s"      if (!($text)) { throw new Error($viol); }"
      .mkString("\n")

    // The harness's own state fetch uses stateSnapshot, so the scan must see
    // it even when no invariant references it.
    val bodyForScan = stepArbs + dispatchCases + invChecks + "stateSnapshot("

    val sb = new StringBuilder
    sb.append(TsRender.Header)
    sb.append("import { test } from \"vitest\";\n")
    sb.append("import fc from \"fast-check\";\n")
    sb.append("import { client } from \"./_client.js\";\n")
    TsRender.runtimeImport(bodyForScan).foreach(sb.append)
    TsRender.predicatesImport(ir, bodyForScan).foreach(sb.append)
    TsRender.strategiesImport(ir, bodyForScan).foreach(sb.append)
    sb.append("\n")
    sb.append("const _RUNS: Record<string, number> = ")
    sb.append("{ smoke: 10, thorough: 25, exhaustive: 75 };\n")
    sb.append("const _STEPS: Record<string, number> = ")
    sb.append("{ smoke: 8, thorough: 20, exhaustive: 40 };\n")
    sb.append("const _P = process.env.SPEC_TEST_PROFILE ?? \"thorough\";\n")
    sb.append("const NUM_RUNS = _RUNS[_P] ?? 25;\n")
    sb.append("const STEP_COUNT = _STEPS[_P] ?? 20;\n\n")
    sb.append("async function dispatch(step: any): Promise<void> {\n")
    sb.append("  switch (step.op) {\n")
    sb.append(dispatchCases)
    sb.append("\n    default: return;\n")
    sb.append("  }\n}\n\n")
    sb.append(
      s"test(${TsLit.str(s"${svcName(ir)} stateful invariants hold under random operation sequences")}, async () => {\n"
    )
    sb.append("  await fc.assert(\n")
    sb.append("    fc.asyncProperty(\n")
    sb.append("      fc.array(\n")
    sb.append("        fc.oneof(\n")
    sb.append(stepArbs)
    sb.append("\n        ),\n")
    sb.append("        { minLength: 1, maxLength: STEP_COUNT },\n")
    sb.append("      ),\n")
    sb.append("      async (steps) => {\n")
    sb.append("        await client.post(\"/admin/reset\");\n")
    sb.append("        for (const step of steps) {\n")
    sb.append("          await dispatch(step);\n")
    sb.append(
      "          const postState = stateSnapshot(await (await client.get(\"/admin/state\"))" +
        ".json()) as any;\n"
    )
    sb.append(invChecks)
    sb.append("\n        }\n")
    sb.append("      },\n")
    sb.append("    ),\n")
    sb.append("    { numRuns: NUM_RUNS },\n")
    sb.append("  );\n")
    sb.append("});\n")
    sb.toString

  private def skipPlaceholder(ir: ServiceIRFull): String =
    s"""|// Auto-generated by spec-to-rest. Do not edit by hand.
        |//
        |// No native stateful test could be built for ${svcName(ir)}: every operation is a
        |// fail-loud stub / has untranslatable inputs, or no global invariant is
        |// black-box assertable. See tests/_testgen_skips.json for the reasons.
        |import { test } from "vitest";
        |
        |test.skip("${svcName(
         ir
       )} stateful: no assertable rules/invariants (see _testgen_skips.json)", () => {});
        |""".stripMargin
