package specrest.testgen

import specrest.codegen.EmittedFile
import specrest.ir.generated.SpecRestGenerated.ServiceIRFull
import specrest.ir.generated.SpecRestGenerated.enmName
import specrest.ir.generated.SpecRestGenerated.enmVariants
import specrest.ir.generated.SpecRestGenerated.expr
import specrest.ir.generated.SpecRestGenerated.fncBody
import specrest.ir.generated.SpecRestGenerated.fncName
import specrest.ir.generated.SpecRestGenerated.fncParams
import specrest.ir.generated.SpecRestGenerated.function_decl
import specrest.ir.generated.SpecRestGenerated.prdBody
import specrest.ir.generated.SpecRestGenerated.prdName
import specrest.ir.generated.SpecRestGenerated.prdParams
import specrest.ir.generated.SpecRestGenerated.predicate_decl
import specrest.ir.generated.SpecRestGenerated.prmName
import specrest.ir.generated.SpecRestGenerated.svcEnums
import specrest.ir.generated.SpecRestGenerated.svcFunctions
import specrest.ir.generated.SpecRestGenerated.svcPredicates

import java.io.ByteArrayOutputStream
import java.nio.charset.StandardCharsets

@SuppressWarnings(Array("org.wartremover.warts.Var", "org.wartremover.warts.Null"))
object TsVitestHarness extends HarnessTemplates:

  private val Root = "testgen-templates/typescript/express"

  private val RuntimeFile        = "tests/_runtime.ts"
  private val ClientFile         = "tests/_client.ts"
  private val RedactionFile      = "tests/_redaction.ts"
  private val StrategiesUserFile = "tests/_strategiesUser.ts"
  private val PredicatesFile     = "tests/_predicates.ts"
  private val RunConformanceFile = "tests/run_conformance.mjs"
  private val VitestConfigFile   = "vitest.config.ts"

  def scaffoldFiles(ir: ServiceIRFull): List[EmittedFile] =
    List(
      EmittedFile(RuntimeFile, loadResource(RuntimeFile)),
      EmittedFile(ClientFile, loadResource(ClientFile)),
      EmittedFile(RedactionFile, loadResource(RedactionFile)),
      EmittedFile(StrategiesUserFile, loadResource(StrategiesUserFile), preserve = true),
      EmittedFile(PredicatesFile, predicates(ir)),
      EmittedFile(VitestConfigFile, loadResource(VitestConfigFile)),
      EmittedFile(RunConformanceFile, loadResource(RunConformanceFile))
    )

  def strategiesPath: String = "tests/_strategies.ts"
  def skipsPath: String      = "tests/_testgen_skips.json"

  def behavioralTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}.behavioral.test.ts"
  def statefulTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}.stateful.test.ts"
  def structuralTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}.structural.test.ts"

  private val PredicatesHeader: String =
    """|// Auto-generated by spec-to-rest. Do not edit by hand.
       |// User-defined functions/predicates translated to TypeScript. `any` is
       |// used for the dynamically-shaped values these helpers operate on.
       |/* eslint-disable @typescript-eslint/no-explicit-any */
       |import {
       |  _diff,
       |  _eq,
       |  _in,
       |  _inter,
       |  _len,
       |  _powerset,
       |  _subset,
       |  _union,
       |} from "./_runtime.js";
       |
       |""".stripMargin

  private def predicates(ir: ServiceIRFull): String =
    PredicatesHeader + renderUserDefinitions(ir)

  private def renderUserDefinitions(ir: ServiceIRFull): String =
    val parts = svcFunctions(ir).map(renderFunction(_, ir)) ++
      svcPredicates(ir).map(renderPredicate(_, ir))
    parts.mkString("")

  private def renderFunction(fn: function_decl, ir: ServiceIRFull): String =
    renderUserDef(fncName(fn), fncParams(fn).map(prmName), fncBody(fn), ir)

  private def renderPredicate(pr: predicate_decl, ir: ServiceIRFull): String =
    renderUserDef(prdName(pr), prdParams(pr).map(prmName), prdBody(pr), ir)

  private def renderUserDef(
      specName: String,
      paramNames: List[String],
      body: expr,
      ir: ServiceIRFull
  ): String =
    val sigParams    = paramNames.map(p => s"$p: any").mkString(", ")
    val nameReserved = TsReservedNames.contains(specName)
    val resParam     = paramNames.find(TsReservedNames.contains)

    def stub(msg: String): String =
      s"export function $specName($sigParams): any {\n" +
        s"  throw new Error(${TsLit.str(msg)});\n}\n\n"

    if nameReserved then
      stub(s"testgen: '$specName' is a TypeScript-reserved name")
    else
      resParam match
        case Some(p) =>
          stub(s"testgen: parameter '$p' of '$specName' is a TypeScript-reserved name")
        case None =>
          val ctx = predicateBodyCtx(paramNames.toSet, ir)
          TsExprBackend.translate(body, ctx) match
            case Translated.Emit(text) =>
              s"export function $specName($sigParams): any {\n  return $text;\n}\n\n"
            case Translated.Skip(reason, _) =>
              stub(s"testgen: cannot translate body of '$specName': $reason")

  private def predicateBodyCtx(params: Set[String], ir: ServiceIRFull): TestCtx =
    TestCtx(
      inputs = params,
      outputs = Set.empty,
      stateFields = Set.empty,
      mapStateFields = Set.empty,
      enumValues = svcEnums(ir).map(e => enmName(e) -> enmVariants(e).toSet).toMap,
      userFunctions = svcFunctions(ir).map(f => fncName(f) -> f).toMap,
      userPredicates = svcPredicates(ir).map(p => prdName(p) -> p).toMap,
      boundVars = Set.empty,
      capture = CaptureMode.PostState
    )

  private def loadResource(relPath: String): String =
    val resourcePath = s"$Root/$relPath"
    val is           = getClass.getClassLoader.getResourceAsStream(resourcePath)
    if is eq null then
      throw new RuntimeException(s"testgen template resource missing: $resourcePath")
    try
      val out    = new ByteArrayOutputStream()
      val buffer = new Array[Byte](8192)
      var read   = is.read(buffer)
      while read != -1 do
        out.write(buffer, 0, read)
        read = is.read(buffer)
      new String(out.toByteArray, StandardCharsets.UTF_8)
    finally is.close()
