package specrest.testgen

import specrest.codegen.EmittedFile
import specrest.ir.generated.SpecRestGenerated.ServiceIRFull
import specrest.ir.generated.SpecRestGenerated.expr

object TsVitestHarness extends HarnessTemplates:

  private val Root = "testgen-templates/typescript/express"

  private val RuntimeFile        = "tests/_runtime.ts"
  private val ClientFile         = "tests/_client.ts"
  private val RedactionFile      = "tests/_redaction.ts"
  private val StrategiesUserFile = "tests/_strategiesUser.ts"
  private val PredicatesFile     = "tests/_predicates.ts"
  private val RunConformanceFile = "tests/run_conformance.mjs"
  private val VitestConfigFile   = "vitest.config.ts"

  def scaffoldFiles(ir: ServiceIRFull): List[EmittedFile] =
    List(
      EmittedFile(RuntimeFile, TemplateResources.load(Root, RuntimeFile)),
      EmittedFile(ClientFile, TemplateResources.load(Root, ClientFile)),
      EmittedFile(RedactionFile, TemplateResources.load(Root, RedactionFile)),
      EmittedFile(
        StrategiesUserFile,
        TemplateResources.load(Root, StrategiesUserFile),
        preserve = true
      ),
      EmittedFile(PredicatesFile, predicates(ir)),
      EmittedFile(VitestConfigFile, TemplateResources.load(Root, VitestConfigFile)),
      EmittedFile(RunConformanceFile, TemplateResources.load(Root, RunConformanceFile))
    )

  def strategiesPath: String = "tests/_strategies.ts"
  def skipsPath: String      = "tests/_testgen_skips.json"

  def behavioralTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}.behavioral.test.ts"
  def statefulTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}.stateful.test.ts"
  def structuralTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}.structural.test.ts"

  private val PredicatesHeader: String =
    """|// Auto-generated by spec-to-rest. Do not edit by hand.
       |// User-defined functions/predicates translated to TypeScript. `any` is
       |// used for the dynamically-shaped values these helpers operate on.
       |/* eslint-disable @typescript-eslint/no-explicit-any */
       |import {
       |  _diff,
       |  _eq,
       |  _in,
       |  _inter,
       |  _len,
       |  _powerset,
       |  _subset,
       |  _union,
       |} from "./_runtime.js";
       |
       |""".stripMargin

  private def predicates(ir: ServiceIRFull): String =
    PredicatesHeader + UserDefs.renderAll(ir)((n, ps, b) => renderUserDef(n, ps, b, ir))

  private def renderUserDef(
      specName: String,
      paramNames: List[String],
      body: expr,
      ir: ServiceIRFull
  ): String =
    val sigParams    = paramNames.map(p => s"$p: any").mkString(", ")
    val nameReserved = TsReservedNames.contains(specName)
    val resParam     = paramNames.find(TsReservedNames.contains)

    def stub(msg: String): String =
      s"export function $specName($sigParams): any {\n" +
        s"  throw new Error(${TsLit.str(msg)});\n}\n\n"

    if nameReserved then
      stub(s"testgen: '$specName' is a TypeScript-reserved name")
    else
      resParam match
        case Some(p) =>
          stub(s"testgen: parameter '$p' of '$specName' is a TypeScript-reserved name")
        case None =>
          val ctx = TestCtx.forPredicateBody(paramNames.toSet, ir)
          TsExprBackend.translate(body, ctx) match
            case Translated.Emit(text) =>
              s"export function $specName($sigParams): any {\n  return $text;\n}\n\n"
            case Translated.Skip(reason, _) =>
              stub(s"testgen: cannot translate body of '$specName': $reason")
