package specrest.testgen

import specrest.codegen.EmittedFile
import specrest.ir.generated.SpecRestGenerated.EnumDeclFull
import specrest.ir.generated.SpecRestGenerated.FunctionDeclFull
import specrest.ir.generated.SpecRestGenerated.ParamDeclFull
import specrest.ir.generated.SpecRestGenerated.PredicateDeclFull
import specrest.ir.generated.SpecRestGenerated.ServiceIRFull
import specrest.ir.generated.SpecRestGenerated.expr_full

import java.io.ByteArrayOutputStream
import java.nio.charset.StandardCharsets

@SuppressWarnings(Array("org.wartremover.warts.Var", "org.wartremover.warts.Null"))
object TsVitestHarness extends HarnessTemplates:

  private val Root = "testgen-templates/typescript/express"

  private val RuntimeFile        = "tests/_runtime.ts"
  private val ClientFile         = "tests/_client.ts"
  private val RedactionFile      = "tests/_redaction.ts"
  private val StrategiesUserFile = "tests/_strategiesUser.ts"
  private val PredicatesFile     = "tests/_predicates.ts"
  private val RunConformanceFile = "tests/run_conformance.mjs"
  private val VitestConfigFile   = "vitest.config.ts"

  def scaffoldFiles(ir: ServiceIRFull): List[EmittedFile] =
    List(
      EmittedFile(RuntimeFile, loadResource(RuntimeFile)),
      EmittedFile(ClientFile, loadResource(ClientFile)),
      EmittedFile(RedactionFile, loadResource(RedactionFile)),
      EmittedFile(StrategiesUserFile, loadResource(StrategiesUserFile)),
      EmittedFile(PredicatesFile, predicates(ir)),
      EmittedFile(VitestConfigFile, loadResource(VitestConfigFile)),
      EmittedFile(RunConformanceFile, loadResource(RunConformanceFile))
    )

  def strategiesPath: String = "tests/_strategies.ts"
  def skipsPath: String      = "tests/_testgen_skips.json"

  def behavioralTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}.behavioral.test.ts"
  def statefulTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}.stateful.test.ts"
  def structuralTestPath(serviceSnake: String): String =
    s"tests/${serviceSnake}.structural.test.ts"

  private val PredicatesHeader: String =
    """|// Auto-generated by spec-to-rest. Do not edit by hand.
       |// User-defined functions/predicates translated to TypeScript. `any` is
       |// used for the dynamically-shaped values these helpers operate on.
       |/* eslint-disable @typescript-eslint/no-explicit-any */
       |import {
       |  _diff,
       |  _eq,
       |  _in,
       |  _inter,
       |  _len,
       |  _powerset,
       |  _subset,
       |  _union,
       |} from "./_runtime.js";
       |
       |""".stripMargin

  private def predicates(ir: ServiceIRFull): String =
    PredicatesHeader + renderUserDefinitions(ir)

  private def renderUserDefinitions(ir: ServiceIRFull): String =
    val parts = ir.l.collect { case _f: FunctionDeclFull => renderFunction(_f, ir) } ++
      ir.m.collect { case _p: PredicateDeclFull => renderPredicate(_p, ir) }
    parts.mkString("")

  private def renderFunction(fn: FunctionDeclFull, ir: ServiceIRFull): String =
    renderUserDef(fn.a, fn.b.collect { case ParamDeclFull(_n, _, _) => _n }, fn.d, ir)

  private def renderPredicate(pr: PredicateDeclFull, ir: ServiceIRFull): String =
    renderUserDef(pr.a, pr.b.collect { case ParamDeclFull(_n, _, _) => _n }, pr.c, ir)

  private def renderUserDef(
      specName: String,
      paramNames: List[String],
      body: expr_full,
      ir: ServiceIRFull
  ): String =
    val sigParams    = paramNames.map(p => s"$p: any").mkString(", ")
    val nameReserved = TsReservedNames.contains(specName)
    val resParam     = paramNames.find(TsReservedNames.contains)

    def stub(msg: String): String =
      s"export function $specName($sigParams): any {\n" +
        s"  throw new Error(${TsLit.str(msg)});\n}\n\n"

    if nameReserved then
      stub(s"testgen: '$specName' is a TypeScript-reserved name")
    else
      resParam match
        case Some(p) =>
          stub(s"testgen: parameter '$p' of '$specName' is a TypeScript-reserved name")
        case None =>
          val ctx = predicateBodyCtx(paramNames.toSet, ir)
          TsExprBackend.translate(body, ctx) match
            case ExprPy.Py(text) =>
              s"export function $specName($sigParams): any {\n  return $text;\n}\n\n"
            case ExprPy.Skip(reason, _) =>
              stub(s"testgen: cannot translate body of '$specName': $reason")

  private def predicateBodyCtx(params: Set[String], ir: ServiceIRFull): TestCtx =
    TestCtx(
      inputs = params,
      outputs = Set.empty,
      stateFields = Set.empty,
      mapStateFields = Set.empty,
      enumValues = ir.d.collect { case e: EnumDeclFull => e.a -> e.b.toSet }.toMap,
      userFunctions = ir.l.collect { case f: FunctionDeclFull => f.a -> f }.toMap,
      userPredicates = ir.m.collect { case p: PredicateDeclFull => p.a -> p }.toMap,
      boundVars = Set.empty,
      capture = CaptureMode.PostState
    )

  private def loadResource(relPath: String): String =
    val resourcePath = s"$Root/$relPath"
    val is           = getClass.getClassLoader.getResourceAsStream(resourcePath)
    if is eq null then
      throw new RuntimeException(s"testgen template resource missing: $resourcePath")
    try
      val out    = new ByteArrayOutputStream()
      val buffer = new Array[Byte](8192)
      var read   = is.read(buffer)
      while read != -1 do
        out.write(buffer, 0, read)
        read = is.read(buffer)
      new String(out.toByteArray, StandardCharsets.UTF_8)
    finally is.close()
