package specrest.verify.cert

import specrest.ir.*

object Emit:

  final case class CertificateBundle(
      moduleName: String,
      header: String,
      theorems: List[String],
      summary: BundleSummary,
      proofsLeanPath: String
  ):
    def renderModule: String =
      val body =
        if theorems.isEmpty then "  -- no certifiable obligations\n"
        else theorems.mkString("\n\n")
      s"$header\n\n$body\n"

    def renderLakefile: String =
      s"""name = "${kebab(moduleName)}"
         |version = "0.1.0"
         |defaultTargets = ["$moduleName"]
         |
         |[[require]]
         |name = "spec-rest-proofs"
         |path = ${quote(proofsLeanPath)}
         |
         |[[lean_lib]]
         |name = "$moduleName"
         |""".stripMargin

    /** Lake reads the toolchain pin from `lean-toolchain` in the workspace root. The cert bundle
      * copies the project's pin verbatim.
      */
    def renderToolchain(toolchainText: String): String = toolchainText

    private def kebab(s: String): String =
      s.replaceAll("([a-z])([A-Z])", "$1-$2").toLowerCase

  final case class BundleSummary(
      totalChecks: Int,
      certifiedChecks: Int,
      stubbedChecks: Int
  )

  /** Compose a bundle for `ir`. `proofsLeanPath` is the absolute path to the in-repo `proofs/lean/`
    * workspace; the generated lakefile.toml will declare a path-based `[[require]]` against it.
    */
  def emit(ir: ServiceIR, proofsLeanPath: String): CertificateBundle =
    val st         = EvalIR.State.demo(ir)
    val moduleName = sanitizeModule(ir.name) + "Cert"

    val invariantTheorems = ir.invariants.zipWithIndex.map: (inv, idx) =>
      renderInvariantTheorem(ir, inv, idx, st)

    val opRequiresTheorems = ir.operations.zipWithIndex.flatMap: (op, opIdx) =>
      op.requires.zipWithIndex.map: (req, reqIdx) =>
        renderOperationRequiresTheorem(ir, op, opIdx, req, reqIdx, st)

    val theorems = invariantTheorems ++ opRequiresTheorems

    val (certified, stubbed) = theorems.foldLeft((0, 0)): (acc, t) =>
      val (c, s) = acc
      // Out-of-subset stubs carry the `OUT OF M_L.1 VERIFIED SUBSET` banner
      // in their docstring; in-subset certs use `cert_decide`. Emitted bundle
      // contains zero `sorry` markers — both stubs discharge via `trivial`.
      if t.contains("OUT OF M_L.1 VERIFIED SUBSET") then (c, s + 1)
      else (c + 1, s)

    val header = renderHeader(ir, moduleName)

    CertificateBundle(
      moduleName = moduleName,
      header = header,
      theorems = theorems,
      summary = BundleSummary(
        totalChecks = theorems.size,
        certifiedChecks = certified,
        stubbedChecks = stubbed
      ),
      proofsLeanPath = proofsLeanPath
    )

  private def renderHeader(ir: ServiceIR, moduleName: String): String =
    s"""import SpecRest.IR
       |import SpecRest.Semantics
       |import SpecRest.Lemmas
       |import SpecRest.Cert
       |
       |/-! Translation-validation certificate for service `${ir.name}`.
       |
       |    Generated by `specrest.verify.cert.Emit`. In-subset checks close
       |    via `cert_decide` (= `native_decide`); out-of-subset checks emit
       |    a trivially-discharged `True` theorem with a `TODO[M_L.4]` marker
       |    in the docstring naming the offending operator. The bundle is
       |    therefore `sorry`-free and `lake build` is silent-clean.
       |
       |    Trust closure: M_L.1 + the `Lean.ofReduceBool` axiom that
       |    `native_decide` introduces. -/
       |
       |namespace $moduleName
       |
       |open SpecRest
       |open SpecRest.Cert""".stripMargin

  private def renderInvariantTheorem(
      ir: ServiceIR,
      inv: InvariantDecl,
      idx: Int,
      st: EvalIR.State
  ): String =
    val displayName = inv.name.getOrElse(s"anon_$idx")
    val theoremName = s"cert_invariant_${idx}_${sanitize(displayName)}"

    VerifiedSubset.classify(inv.expr) match
      case VerifiedSubset.SubsetStatus.OutOfSubset(reason) =>
        renderOutOfSubsetStub(
          theoremName,
          s"invariant `$displayName` for service `${ir.name}`",
          reason
        )

      case VerifiedSubset.SubsetStatus.InSubset =>
        EvalIR.evalInvariantBody(ir, st, Nil, inv.expr) match
          case None =>
            // Reducer got stuck (e.g., relation reference with no demo data).
            renderOutOfSubsetStub(
              theoremName,
              s"invariant `$displayName` for service `${ir.name}`",
              "closed reducer stuck on placeholder demo state"
            )
          case Some(actualBool) =>
            val schemaTerm = renderSchemaLit(ir)
            val stateTerm  = renderStateLit(ir)
            val invTerm    = renderInvariantDecl(inv, displayName)
            val expected   = if actualBool then "true" else "false"
            s"""/-- Invariant `$displayName` for service `${ir.name}`. -/
               |theorem $theoremName :
               |    evalInvariant
               |        $schemaTerm
               |        $stateTerm
               |        []
               |        $invTerm
               |      = some $expected := by
               |  cert_decide""".stripMargin

  private def renderOperationRequiresTheorem(
      ir: ServiceIR,
      op: OperationDecl,
      opIdx: Int,
      req: Expr,
      reqIdx: Int,
      st: EvalIR.State
  ): String =
    val theoremName =
      s"cert_op_${opIdx}_${sanitize(op.name)}_requires_$reqIdx"

    VerifiedSubset.classify(req) match
      case VerifiedSubset.SubsetStatus.OutOfSubset(reason) =>
        renderOutOfSubsetStub(
          theoremName,
          s"requires[$reqIdx] of operation `${op.name}` in `${ir.name}`",
          reason
        )

      case VerifiedSubset.SubsetStatus.InSubset =>
        EvalIR.evalRequires(ir, st, Nil, List(req)) match
          case None =>
            renderOutOfSubsetStub(
              theoremName,
              s"requires[$reqIdx] of operation `${op.name}` in `${ir.name}`",
              "closed reducer stuck on placeholder demo state"
            )
          case Some(actualBool) =>
            val schemaTerm = renderSchemaLit(ir)
            val stateTerm  = renderStateLit(ir)
            val reqTerm    = renderExpr(req)
            val expected   = if actualBool then "true" else "false"
            s"""/-- Requires #$reqIdx of operation `${op.name}` in `${ir.name}`. -/
               |theorem $theoremName :
               |    evalRequiresAll
               |        $schemaTerm
               |        $stateTerm
               |        []
               |        [$reqTerm]
               |      = some $expected := by
               |  cert_decide""".stripMargin

  /** Out-of-subset cert: emit a trivially-discharged `True` theorem. The cert carries the
    * missing-operator metadata in its docstring and the trailing `TODO[M_L.4]` comment, but its
    * body is `trivial` so the emitted bundle has zero `sorry` markers and `lake build` is
    * silent-clean.
    */
  private def renderOutOfSubsetStub(
      theoremName: String,
      what: String,
      reason: String
  ): String =
    s"""/-- $what — OUT OF M_L.1 VERIFIED SUBSET: $reason.
       |    This certificate carries no proof obligation about the spec; it
       |    only records that the case is recognised and queued. The real
       |    obligation lands when the offending operator joins the verified
       |    subset (see `TODO[M_L.4]` below). -/
       |theorem $theoremName : True := trivial
       |
       |-- TODO[M_L.4]: $reason — re-emit this certificate once the
       |-- relevant operator joins the verified subset.""".stripMargin

  private def renderSchemaLit(ir: ServiceIR): String =
    if ir.enums.isEmpty && ir.entities.isEmpty then "Schema.empty"
    else
      val enumLits = ir.enums
        .map(d => s"""{ name := ${quote(d.name)}, members := ${renderStringList(d.values)} }""")
        .mkString(", ")
      val entityLits = ir.entities
        .map(d => s"""{ name := ${quote(d.name)}, fields := [] }""")
        .mkString(", ")
      s"""({ enums := [$enumLits], entities := [$entityLits] } : Schema)"""

  private def renderStateLit(ir: ServiceIR): String =
    val st = EvalIR.State.demo(ir)
    if st.scalars.isEmpty && st.relations.isEmpty then "State.empty"
    else
      val scalars = st.scalars
        .map: (name, value) =>
          s"""(${quote(name)}, ${renderValueLit(value)})"""
        .mkString(", ")
      s"""({ scalars := [$scalars], relations := [] } : State)"""

  private def renderValueLit(v: EvalIR.Value): String = v match
    case EvalIR.Value.VBool(b)        => s".vBool $b"
    case EvalIR.Value.VInt(n)         => s".vInt ($n : Int)"
    case EvalIR.Value.VEnum(en, mem)  => s".vEnum ${quote(en)} ${quote(mem)}"
    case EvalIR.Value.VEntity(en, id) => s".vEntity ${quote(en)} ${quote(id)}"

  private def renderInvariantDecl(inv: InvariantDecl, displayName: String): String =
    val body = renderExpr(inv.expr)
    s"""({ name := ${quote(displayName)}, body := $body } : InvariantDecl)"""

  private def renderExpr(expr: Expr): String = expr match
    case Expr.BoolLit(v, _)               => s"(.boolLit $v)"
    case Expr.IntLit(v, _)                => s"(.intLit ($v : Int))"
    case Expr.Identifier(name, _)         => s"(.ident ${quote(name)})"
    case Expr.UnaryOp(UnOp.Not, op, _)    => s"(.unNot ${renderExpr(op)})"
    case Expr.UnaryOp(UnOp.Negate, op, _) => s"(.unNeg ${renderExpr(op)})"
    case Expr.UnaryOp(UnOp.Cardinality, Expr.Identifier(rel, _), _) =>
      s"(.cardRel ${quote(rel)})"
    case Expr.UnaryOp(UnOp.Cardinality, _, _) =>
      unreachableShape("UnaryOp(Cardinality): non-Identifier operand")
    case Expr.BinaryOp(op, l, r, _) =>
      val lT = renderExpr(l)
      val rT = renderExpr(r)
      op match
        case BinOp.And     => s"(.boolBin .and $lT $rT)"
        case BinOp.Or      => s"(.boolBin .or $lT $rT)"
        case BinOp.Implies => s"(.boolBin .implies $lT $rT)"
        case BinOp.Iff     => s"(.boolBin .iff $lT $rT)"
        case BinOp.Eq      => s"(.cmp .eq $lT $rT)"
        case BinOp.Neq     => s"(.cmp .neq $lT $rT)"
        case BinOp.Lt      => s"(.cmp .lt $lT $rT)"
        case BinOp.Le      => s"(.cmp .le $lT $rT)"
        case BinOp.Gt      => s"(.cmp .gt $lT $rT)"
        case BinOp.Ge      => s"(.cmp .ge $lT $rT)"
        case BinOp.Add     => s"(.arith .add $lT $rT)"
        case BinOp.Sub     => s"(.arith .sub $lT $rT)"
        case BinOp.Mul     => s"(.arith .mul $lT $rT)"
        case BinOp.Div     => s"(.arith .div $lT $rT)"
        case BinOp.In =>
          r match
            case Expr.Identifier(rel, _) => s"(.member $lT ${quote(rel)})"
            // VerifiedSubset.classify rejects this shape; reaching here
            // implies a classifier-vs-renderer drift.
            case _ => unreachableShape("BinaryOp(In): non-identifier rhs")
        case BinOp.NotIn =>
          // NotIn(elem, rel)  ≡  Not(In(elem, rel)). Emitter-side composition
          // mirrors Translator.scala:632-636 which renders the same shape.
          r match
            case Expr.Identifier(rel, _) => s"(.unNot (.member $lT ${quote(rel)}))"
            case _                       => unreachableShape("BinaryOp(NotIn): non-identifier rhs")
        case _ => unreachableShape(s"BinaryOp.$op out of subset")
    case Expr.Let(v, value, body, _) =>
      s"(.letIn ${quote(v)} ${renderExpr(value)} ${renderExpr(body)})"
    case Expr.EnumAccess(Expr.Identifier(en, _), member, _) =>
      s"(.enumAccess ${quote(en)} ${quote(member)})"
    case _: Expr.EnumAccess =>
      unreachableShape("EnumAccess: non-Identifier base")
    case Expr.Prime(inner, _) => s"(.prime ${renderExpr(inner)})"
    case Expr.Pre(inner, _)   => s"(.pre ${renderExpr(inner)})"
    case Expr.Quantifier(QuantKind.All, bindings, body, _) =>
      bindings match
        case List(QuantifierBinding(v, Expr.Identifier(en, _), _, _)) =>
          s"(.forallEnum ${quote(v)} ${quote(en)} ${renderExpr(body)})"
        case _ =>
          unreachableShape("Quantifier(All): not single-binding over identifier")
    case Expr.Quantifier(QuantKind.No, bindings, body, _) =>
      // No x, P  ≡  ∀ x, ¬ P
      bindings match
        case List(QuantifierBinding(v, Expr.Identifier(en, _), _, _)) =>
          s"(.forallEnum ${quote(v)} ${quote(en)} (.unNot ${renderExpr(body)}))"
        case _ =>
          unreachableShape("Quantifier(No): not single-binding over identifier")
    case Expr.Quantifier(QuantKind.Some, bindings, body, _) =>
      // ∃ x, P  ≡  ¬ ∀ x, ¬ P
      bindings match
        case List(QuantifierBinding(v, Expr.Identifier(en, _), _, _)) =>
          s"(.unNot (.forallEnum ${quote(v)} ${quote(en)} (.unNot ${renderExpr(body)})))"
        case _ =>
          unreachableShape("Quantifier(Some): not single-binding over identifier")
    case Expr.Quantifier(QuantKind.Exists, bindings, body, _) =>
      bindings match
        case List(QuantifierBinding(v, Expr.Identifier(en, _), _, _)) =>
          s"(.unNot (.forallEnum ${quote(v)} ${quote(en)} (.unNot ${renderExpr(body)})))"
        case _ =>
          unreachableShape("Quantifier(Exists): not single-binding over identifier")
    case _ => unreachableShape("expression out of M_L.1 verified subset")

  /** Bare block comments are not valid Lean expression terms. The `VerifiedSubset.classify`
    * predicate is supposed to reject every shape the renderer can't produce, so reaching this
    * branch implies a classifier-vs-renderer drift. Emit a syntactically-valid placeholder carrying
    * the diagnosis as an inline comment so `lake build` fails loudly with the diagnosis rather than
    * at parse-time.
    */
  private def unreachableShape(reason: String): String =
    s"(.boolLit false /- UNRENDERABLE: $reason -/)"

  private def quote(s: String): String =
    val escaped = s.replace("\\", "\\\\").replace("\"", "\\\"")
    s"\"$escaped\""

  private def renderStringList(xs: List[String]): String =
    xs.map(quote).mkString("[", ", ", "]")

  private def sanitize(s: String): String =
    s.flatMap: c =>
      if c.isLetterOrDigit || c == '_' then c.toString else "_"

  private def sanitizeModule(s: String): String =
    val cleaned = sanitize(s)
    if cleaned.isEmpty || !cleaned.head.isLetter then "Spec" + cleaned
    else cleaned
