package specrest.verify.cert

import specrest.ir.*

object Emit:

  final case class CertificateBundle(
      moduleName: String,
      header: String,
      theorems: List[String],
      summary: BundleSummary,
      proofsLeanPath: String
  ):
    def renderModule: String =
      val body =
        if theorems.isEmpty then "  -- no certifiable obligations\n"
        else theorems.mkString("\n\n")
      s"$header\n\n$body\n"

    def renderLakefile: String =
      s"""name = "${kebab(moduleName)}"
         |version = "0.1.0"
         |defaultTargets = ["$moduleName"]
         |
         |[[require]]
         |name = "spec-rest-proofs"
         |path = ${quote(proofsLeanPath)}
         |
         |[[lean_lib]]
         |name = "$moduleName"
         |""".stripMargin

    /** Lake reads the toolchain pin from `lean-toolchain` in the workspace root. The cert bundle
      * copies the project's pin verbatim.
      */
    def renderToolchain(toolchainText: String): String = toolchainText

    private def kebab(s: String): String =
      s.replaceAll("([a-z])([A-Z])", "$1-$2").toLowerCase

  final case class BundleSummary(
      totalChecks: Int,
      certifiedChecks: Int,
      stubbedChecks: Int
  )

  /** Compose a bundle for `ir`. `proofsLeanPath` is the absolute path to the in-repo `proofs/lean/`
    * workspace; the generated lakefile.toml will declare a path-based `[[require]]` against it.
    */
  def emit(ir: ServiceIR, proofsLeanPath: String): CertificateBundle =
    val st         = EvalIR.State.demo(ir)
    val moduleName = sanitizeModule(ir.name) + "Cert"

    val invariantTheorems = ir.invariants.zipWithIndex.map: (inv, idx) =>
      renderInvariantTheorem(ir, inv, idx, st)

    val opRequiresTheorems = ir.operations.zipWithIndex.flatMap: (op, opIdx) =>
      op.requires.zipWithIndex.map: (req, reqIdx) =>
        renderOperationRequiresTheorem(ir, op, opIdx, req, reqIdx, st)

    // M_L.4.b-ext Phase 5.c: per-(operation × invariant) preservation cert.
    // Operations with no `ensures` skip preservation entirely — there's
    // nothing to claim about the post-state. Operations with at least one
    // ensures get one preservation theorem per invariant; the renderer
    // declines (stub) when ensures synthesis can't recognise the shape.
    val opPreservationTheorems = ir.operations.zipWithIndex.flatMap: (op, opIdx) =>
      if op.ensures.isEmpty then Nil
      else
        ir.invariants.zipWithIndex.map: (inv, invIdx) =>
          renderOperationPreservesInvariantTheorem(ir, op, opIdx, inv, invIdx, st)

    val theorems = invariantTheorems ++ opRequiresTheorems ++ opPreservationTheorems

    val (certified, stubbed) = theorems.foldLeft((0, 0)): (acc, t) =>
      val (c, s) = acc
      // Out-of-subset stubs carry the `OUT OF M_L.1 VERIFIED SUBSET` banner
      // in their docstring; in-subset certs use `cert_decide`. Emitted bundle
      // contains zero `sorry` markers — both stubs discharge via `trivial`.
      if t.contains("OUT OF M_L.1 VERIFIED SUBSET") then (c, s + 1)
      else (c + 1, s)

    val header = renderHeader(ir, moduleName)

    CertificateBundle(
      moduleName = moduleName,
      header = header,
      theorems = theorems,
      summary = BundleSummary(
        totalChecks = theorems.size,
        certifiedChecks = certified,
        stubbedChecks = stubbed
      ),
      proofsLeanPath = proofsLeanPath
    )

  private def renderHeader(ir: ServiceIR, moduleName: String): String =
    s"""import SpecRest.IR
       |import SpecRest.Semantics
       |import SpecRest.Lemmas
       |import SpecRest.Cert
       |
       |/-! Translation-validation certificate for service `${ir.name}`.
       |
       |    Generated by `specrest.verify.cert.Emit`. In-subset checks close
       |    via `cert_decide` (= `native_decide`); out-of-subset checks emit
       |    a trivially-discharged `True` theorem with a `TODO[M_L.4]` marker
       |    in the docstring naming the offending operator. The bundle is
       |    therefore `sorry`-free and `lake build` is silent-clean.
       |
       |    Trust closure: M_L.1 + the `Lean.ofReduceBool` axiom that
       |    `native_decide` introduces. -/
       |
       |namespace $moduleName
       |
       |open SpecRest
       |open SpecRest.Cert""".stripMargin

  private def renderInvariantTheorem(
      ir: ServiceIR,
      inv: InvariantDecl,
      idx: Int,
      st: EvalIR.State
  ): String =
    val displayName = inv.name.getOrElse(s"anon_$idx")
    val theoremName = s"cert_invariant_${idx}_${sanitize(displayName)}"

    VerifiedSubset.classify(inv.expr) match
      case VerifiedSubset.SubsetStatus.OutOfSubset(reason) =>
        renderOutOfSubsetStub(
          theoremName,
          s"invariant `$displayName` for service `${ir.name}`",
          reason
        )

      case VerifiedSubset.SubsetStatus.InSubset =>
        EvalIR.evalInvariantBody(ir, st, Nil, inv.expr) match
          case None =>
            // Reducer got stuck (e.g., relation reference with no demo data).
            renderOutOfSubsetStub(
              theoremName,
              s"invariant `$displayName` for service `${ir.name}`",
              "closed reducer stuck on placeholder demo state"
            )
          case Some(actualBool) =>
            val enumNames  = ir.enums.map(_.name).toSet
            val schemaTerm = renderSchemaLit(ir)
            val stateTerm  = renderStateLit(ir)
            val invTerm    = renderInvariantDecl(inv, displayName, enumNames)
            val expected   = if actualBool then "true" else "false"
            s"""/-- Invariant `$displayName` for service `${ir.name}`. -/
               |theorem $theoremName :
               |    evalInvariant
               |        $schemaTerm
               |        $stateTerm
               |        []
               |        $invTerm
               |      = some $expected := by
               |  cert_decide""".stripMargin

  private def renderOperationRequiresTheorem(
      ir: ServiceIR,
      op: OperationDecl,
      opIdx: Int,
      req: Expr,
      reqIdx: Int,
      st: EvalIR.State
  ): String =
    val theoremName =
      s"cert_op_${opIdx}_${sanitize(op.name)}_requires_$reqIdx"

    VerifiedSubset.classify(req) match
      case VerifiedSubset.SubsetStatus.OutOfSubset(reason) =>
        renderOutOfSubsetStub(
          theoremName,
          s"requires[$reqIdx] of operation `${op.name}` in `${ir.name}`",
          reason
        )

      case VerifiedSubset.SubsetStatus.InSubset =>
        EvalIR.evalRequires(ir, st, Nil, List(req)) match
          case None =>
            renderOutOfSubsetStub(
              theoremName,
              s"requires[$reqIdx] of operation `${op.name}` in `${ir.name}`",
              "closed reducer stuck on placeholder demo state"
            )
          case Some(actualBool) =>
            val enumNames  = ir.enums.map(_.name).toSet
            val schemaTerm = renderSchemaLit(ir)
            val stateTerm  = renderStateLit(ir)
            val reqTerm    = renderExpr(req, enumNames)
            val expected   = if actualBool then "true" else "false"
            s"""/-- Requires #$reqIdx of operation `${op.name}` in `${ir.name}`. -/
               |theorem $theoremName :
               |    evalRequiresAll
               |        $schemaTerm
               |        $stateTerm
               |        []
               |        [$reqTerm]
               |      = some $expected := by
               |  cert_decide""".stripMargin

  /** M_L.4.b-ext Phase 5.c: emit one preservation cert per (operation × invariant) pair. Renders a
    * closed `evalPreservation` claim: in the operation's pre- state, if `requires` hold, the
    * `invariant` must still hold in the post- state synthesised from `ensures`. Vacuous when
    * `requires` is false on the demo state.
    *
    * Stubs out (with a `TODO[M_L.4]` marker) when:
    *   - The invariant's body is out-of-subset.
    *   - Any of the operation's `requires` or `ensures` clauses are out-of-subset.
    *   - `EvalIR.synthesizePostState` declines (ensures shape unrecognised).
    *   - The closed evaluator returns `none` on the demo pre/post pair.
    */
  private def renderOperationPreservesInvariantTheorem(
      ir: ServiceIR,
      op: OperationDecl,
      opIdx: Int,
      inv: InvariantDecl,
      invIdx: Int,
      demoState: EvalIR.State
  ): String =
    val invName = inv.name.getOrElse(s"anon_$invIdx")
    val theoremName =
      s"cert_op_${opIdx}_${sanitize(op.name)}_preserves_${invIdx}_${sanitize(invName)}"
    val what = s"`${op.name}` preserves invariant `$invName` in `${ir.name}`"

    val invStatus = VerifiedSubset.classify(inv.expr)
    val reqsStatus =
      op.requires.foldLeft[VerifiedSubset.SubsetStatus](VerifiedSubset.SubsetStatus.InSubset):
        (acc, r) => chooseWorseStatus(acc, VerifiedSubset.classify(r))
    val ensuresStatus =
      op.ensures.foldLeft[VerifiedSubset.SubsetStatus](VerifiedSubset.SubsetStatus.InSubset):
        (acc, e) => chooseWorseStatus(acc, VerifiedSubset.classify(e))

    val combined =
      chooseWorseStatus(invStatus, chooseWorseStatus(reqsStatus, ensuresStatus))

    combined match
      case VerifiedSubset.SubsetStatus.OutOfSubset(reason) =>
        renderOutOfSubsetStub(theoremName, what, reason)
      case VerifiedSubset.SubsetStatus.InSubset =>
        // M_L.4.b-ext Phase 5.d: per-op pre-state seeding. Pick a pre-state
        // where requires AND invariant both hold (or fall back to requires-only,
        // then to demo). This makes preservation certs non-vacuous when
        // possible — the demo state may not satisfy the operation's requires
        // (e.g., safe_counter Decrement's `count > 0` rejects pre.count = 0).
        val pre = EvalIR.seedPreStateForOp(ir, op, inv, demoState)
        EvalIR.synthesizePostState(ir, op, pre) match
          case None =>
            renderOutOfSubsetStub(
              theoremName,
              what,
              "ensures synthesis declined — non-primed-equality clause shape"
            )
          case Some(post) =>
            val sp = EvalIR.StatePair(pre, post)
            EvalIR.evalInvariantBodyAt(EvalIR.StateMode.Post, ir, sp, Nil, inv.expr) match
              case None =>
                renderOutOfSubsetStub(
                  theoremName,
                  what,
                  "closed reducer stuck on synthesised post-state"
                )
              case Some(_) =>
                EvalIR.evalRequiresAt(EvalIR.StateMode.Pre, ir, sp, Nil, op.requires) match
                  case None =>
                    renderOutOfSubsetStub(
                      theoremName,
                      what,
                      "closed reducer stuck on requires in pre-state"
                    )
                  case Some(reqsHold) =>
                    val expectedBool =
                      if !reqsHold then true
                      else
                        EvalIR
                          .evalInvariantBodyAt(EvalIR.StateMode.Post, ir, sp, Nil, inv.expr)
                          .getOrElse(false)
                    val enumNames     = ir.enums.map(_.name).toSet
                    val schemaTerm    = renderSchemaLit(ir)
                    val statePairTerm = renderStatePairLit(pre, post)
                    val invTerm       = renderInvariantDecl(inv, invName, enumNames)
                    val reqsTerm =
                      op.requires.map(r => renderExpr(r, enumNames)).mkString(", ")
                    val expected = if expectedBool then "true" else "false"
                    s"""/-- $what — preservation under ensures-driven post-state synthesis. -/
                       |theorem $theoremName :
                       |    evalPreservation
                       |        $schemaTerm
                       |        $statePairTerm
                       |        []
                       |        [$reqsTerm]
                       |        $invTerm
                       |      = some $expected := by
                       |  cert_decide""".stripMargin

  private def chooseWorseStatus(
      a: VerifiedSubset.SubsetStatus,
      b: VerifiedSubset.SubsetStatus
  ): VerifiedSubset.SubsetStatus = (a, b) match
    case (VerifiedSubset.SubsetStatus.InSubset, x)             => x
    case (x, VerifiedSubset.SubsetStatus.InSubset)             => x
    case (out @ VerifiedSubset.SubsetStatus.OutOfSubset(_), _) => out

  /** Out-of-subset cert: emit a trivially-discharged `True` theorem. The cert carries the
    * missing-operator metadata in its docstring and the trailing `TODO[M_L.4]` comment, but its
    * body is `trivial` so the emitted bundle has zero `sorry` markers and `lake build` is
    * silent-clean.
    */
  private def renderOutOfSubsetStub(
      theoremName: String,
      what: String,
      reason: String
  ): String =
    s"""/-- $what — OUT OF M_L.1 VERIFIED SUBSET: $reason.
       |    This certificate carries no proof obligation about the spec; it
       |    only records that the case is recognised and queued. The real
       |    obligation lands when the offending operator joins the verified
       |    subset (see `TODO[M_L.4]` below). -/
       |theorem $theoremName : True := trivial
       |
       |-- TODO[M_L.4]: $reason — re-emit this certificate once the
       |-- relevant operator joins the verified subset.""".stripMargin

  private def renderSchemaLit(ir: ServiceIR): String =
    if ir.enums.isEmpty && ir.entities.isEmpty then "Schema.empty"
    else
      val enumLits = ir.enums
        .map(d => s"""{ name := ${quote(d.name)}, members := ${renderStringList(d.values)} }""")
        .mkString(", ")
      val entityLits = ir.entities
        .map(d => s"""{ name := ${quote(d.name)}, fields := [] }""")
        .mkString(", ")
      s"""({ enums := [$enumLits], entities := [$entityLits] } : Schema)"""

  private def renderStateLit(ir: ServiceIR): String =
    renderStateLitOf(EvalIR.State.demo(ir))

  /** M_L.4.b-ext Phase 5.c: render an arbitrary `EvalIR.State` as a Lean `State` literal. Factored
    * from `renderStateLit` so the preservation cert renderer can emit synthesised post-states
    * alongside the demo pre-state.
    */
  private def renderStateLitOf(st: EvalIR.State): String =
    if st.scalars.isEmpty && st.relations.isEmpty && st.lookups.isEmpty
      && st.entityFields.isEmpty
    then "State.empty"
    else
      val scalars = st.scalars
        .map: (name, value) =>
          s"""(${quote(name)}, ${renderValueLit(value)})"""
        .mkString(", ")
      val relations = st.relations
        .map: (name, dom) =>
          val domLit = dom.map(renderValueLit).mkString(", ")
          s"""(${quote(name)}, [$domLit])"""
        .mkString(", ")
      val lookups = st.lookups
        .map: (name, pairs) =>
          val pairsLit = pairs
            .map((k, v) => s"(${renderValueLit(k)}, ${renderValueLit(v)})")
            .mkString(", ")
          s"""(${quote(name)}, [$pairsLit])"""
        .mkString(", ")
      val entityFields = st.entityFields
        .map: (name, fields) =>
          val fieldsLit = fields
            .map((f, v) => s"(${quote(f)}, ${renderValueLit(v)})")
            .mkString(", ")
          s"""(${quote(name)}, [$fieldsLit])"""
        .mkString(", ")
      s"""({ scalars := [$scalars], relations := [$relations], lookups := [$lookups], entityFields := [$entityFields] } : State)"""

  /** M_L.4.b-ext Phase 5.c: render a `(pre, post)` pair as a Lean `StatePair`. Used by the
    * operation invariant-preservation cert; the pre-state is the demo state, the post-state is the
    * ensures-driven synthesis from `EvalIR.synthesizePostState`.
    */
  private def renderStatePairLit(pre: EvalIR.State, post: EvalIR.State): String =
    s"({ pre := ${renderStateLitOf(pre)}, post := ${renderStateLitOf(post)} } : StatePair)"

  private def renderValueLit(v: EvalIR.Value): String = v match
    case EvalIR.Value.VBool(b)        => s".vBool $b"
    case EvalIR.Value.VInt(n)         => s".vInt ($n : Int)"
    case EvalIR.Value.VEnum(en, mem)  => s".vEnum ${quote(en)} ${quote(mem)}"
    case EvalIR.Value.VEntity(en, id) => s".vEntity ${quote(en)} ${quote(id)}"
    case EvalIR.Value.VSet(members) =>
      s".vSet [${members.map(renderValueLit).mkString(", ")}]"
    case EvalIR.Value.VEntityWith(base, fld, value) =>
      // Mirrors Lean `Value.vEntityWith` chain ctor.
      s".vEntityWith ${renderValueLit(base)} ${quote(fld)} ${renderValueLit(value)}"

  private def renderInvariantDecl(
      inv: InvariantDecl,
      displayName: String,
      enumNames: Set[String]
  ): String =
    val body = renderExpr(inv.expr, enumNames)
    s"""({ name := ${quote(displayName)}, body := $body } : InvariantDecl)"""

  private def renderExpr(expr: Expr, enumNames: Set[String]): String = expr match
    case Expr.BoolLit(v, _)               => s"(.boolLit $v)"
    case Expr.IntLit(v, _)                => s"(.intLit ($v : Int))"
    case Expr.Identifier(name, _)         => s"(.ident ${quote(name)})"
    case Expr.UnaryOp(UnOp.Not, op, _)    => s"(.unNot ${renderExpr(op, enumNames)})"
    case Expr.UnaryOp(UnOp.Negate, op, _) => s"(.unNeg ${renderExpr(op, enumNames)})"
    case Expr.UnaryOp(UnOp.Cardinality, Expr.Identifier(rel, _), _) =>
      s"(.cardRel ${quote(rel)})"
    case Expr.UnaryOp(UnOp.Cardinality, _, _) =>
      unreachableShape("UnaryOp(Cardinality): non-Identifier operand")
    case Expr.BinaryOp(op, l, r, _) =>
      val lT = renderExpr(l, enumNames)
      val rT = renderExpr(r, enumNames)
      op match
        case BinOp.And     => s"(.boolBin .and $lT $rT)"
        case BinOp.Or      => s"(.boolBin .or $lT $rT)"
        case BinOp.Implies => s"(.boolBin .implies $lT $rT)"
        case BinOp.Iff     => s"(.boolBin .iff $lT $rT)"
        case BinOp.Eq      => s"(.cmp .eq $lT $rT)"
        case BinOp.Neq     => s"(.cmp .neq $lT $rT)"
        case BinOp.Lt      => s"(.cmp .lt $lT $rT)"
        case BinOp.Le      => s"(.cmp .le $lT $rT)"
        case BinOp.Gt      => s"(.cmp .gt $lT $rT)"
        case BinOp.Ge      => s"(.cmp .ge $lT $rT)"
        case BinOp.Add     => s"(.arith .add $lT $rT)"
        case BinOp.Sub     => s"(.arith .sub $lT $rT)"
        case BinOp.Mul     => s"(.arith .mul $lT $rT)"
        case BinOp.Div     => s"(.arith .div $lT $rT)"
        case BinOp.Union   => s"(.setBin .union $lT $rT)"
        case BinOp.Intersect =>
          s"(.setBin .intersect $lT $rT)"
        case BinOp.Diff => s"(.setBin .diff $lT $rT)"
        case BinOp.In =>
          r match
            case Expr.Identifier(rel, _) => s"(.member $lT ${quote(rel)})"
            case _                       => s"(.setMember $lT $rT)"
        case BinOp.NotIn =>
          // NotIn(elem, rel)  ≡  Not(In(elem, rel)). Emitter-side composition
          // mirrors Translator.scala:632-636 which renders the same shape.
          r match
            case Expr.Identifier(rel, _) => s"(.unNot (.member $lT ${quote(rel)}))"
            case _                       => s"(.unNot (.setMember $lT $rT))"
        case BinOp.Subset =>
          // Subset(r1, r2)  ≡  ∀ x ∈ r1, x ∈ r2. Pure emit-time composition over
          // M_L.4.f forallRel + M_L.2 member. The bound variable name is unique to
          // this lowering and shadows safely (List.lookup finds the head binding).
          (l, r) match
            case (Expr.Identifier(r1, _), Expr.Identifier(r2, _)) =>
              s"(.forallRel \"_subset_x\" ${quote(r1)} (.member (.ident \"_subset_x\") ${quote(r2)}))"
            case _ =>
              unreachableShape("BinaryOp(Subset): non-identifier operand(s)")
    case Expr.Let(v, value, body, _) =>
      s"(.letIn ${quote(v)} ${renderExpr(value, enumNames)} ${renderExpr(body, enumNames)})"
    case Expr.EnumAccess(Expr.Identifier(en, _), member, _) =>
      s"(.enumAccess ${quote(en)} ${quote(member)})"
    case _: Expr.EnumAccess =>
      unreachableShape("EnumAccess: non-Identifier base")
    case Expr.Prime(inner, _) => s"(.prime ${renderExpr(inner, enumNames)})"
    case Expr.Pre(inner, _)   => s"(.pre ${renderExpr(inner, enumNames)})"
    case Expr.Index(Expr.Identifier(rel, _), keyExpr, _) =>
      s"(.indexRel ${quote(rel)} ${renderExpr(keyExpr, enumNames)})"
    case _: Expr.Index =>
      unreachableShape("Index: non-identifier base")
    case Expr.FieldAccess(base, field, _) =>
      // M_L.4.k: render the base as a sub-term so the Lean eval can chase
      // arbitrary entity-valued expressions (Identifier, Index, chained
      // FieldAccess, quantifier-bound vars) through the id-keyed table.
      s"(.fieldAccess ${renderExpr(base, enumNames)} ${quote(field)})"
    case Expr.With(base, updates, _) =>
      // M_L.4.b-ext Phase 4b: lower multi-field record-update to a left-fold
      // of single-field `.withRec` Lean ctors. Mirrors Translator.scala:1061-1098
      // shape; Phase 4b's Skolem semantics close in `Soundness.lean`.
      updates.foldLeft(renderExpr(base, enumNames)): (acc, upd) =>
        s"(.withRec $acc ${quote(upd.name)} ${renderExpr(upd.value, enumNames)})"
    case Expr.SetLiteral(elements, _) =>
      renderSetLiteral(elements, enumNames)
    case Expr.Quantifier(QuantKind.All, bindings, body, _) =>
      bindings match
        case List(QuantifierBinding(v, Expr.Identifier(name, _), _, _)) =>
          val ctor = if enumNames.contains(name) then "forallEnum" else "forallRel"
          s"(.$ctor ${quote(v)} ${quote(name)} ${renderExpr(body, enumNames)})"
        case _ =>
          unreachableShape("Quantifier(All): not single-binding over identifier")
    case Expr.Quantifier(QuantKind.No, bindings, body, _) =>
      // No x, P  ≡  ∀ x, ¬ P
      bindings match
        case List(QuantifierBinding(v, Expr.Identifier(name, _), _, _)) =>
          val ctor = if enumNames.contains(name) then "forallEnum" else "forallRel"
          s"(.$ctor ${quote(v)} ${quote(name)} (.unNot ${renderExpr(body, enumNames)}))"
        case _ =>
          unreachableShape("Quantifier(No): not single-binding over identifier")
    case Expr.Quantifier(QuantKind.Some, bindings, body, _) =>
      // ∃ x, P  ≡  ¬ ∀ x, ¬ P
      bindings match
        case List(QuantifierBinding(v, Expr.Identifier(name, _), _, _)) =>
          val ctor = if enumNames.contains(name) then "forallEnum" else "forallRel"
          s"(.unNot (.$ctor ${quote(v)} ${quote(name)} (.unNot ${renderExpr(body, enumNames)})))"
        case _ =>
          unreachableShape("Quantifier(Some): not single-binding over identifier")
    case Expr.Quantifier(QuantKind.Exists, bindings, body, _) =>
      bindings match
        case List(QuantifierBinding(v, Expr.Identifier(name, _), _, _)) =>
          val ctor = if enumNames.contains(name) then "forallEnum" else "forallRel"
          s"(.unNot (.$ctor ${quote(v)} ${quote(name)} (.unNot ${renderExpr(body, enumNames)})))"
        case _ =>
          unreachableShape("Quantifier(Exists): not single-binding over identifier")
    case _ => unreachableShape("expression out of M_L.1 verified subset")

  /** Bare block comments are not valid Lean expression terms. The `VerifiedSubset.classify`
    * predicate is supposed to reject every shape the renderer can't produce, so reaching this
    * branch implies a classifier-vs-renderer drift. Emit a syntactically-valid placeholder carrying
    * the diagnosis as an inline comment so `lake build` fails loudly with the diagnosis rather than
    * at parse-time.
    */
  private def unreachableShape(reason: String): String =
    s"(.boolLit false /- UNRENDERABLE: $reason -/)"

  private def renderSetLiteral(elements: List[Expr], enumNames: Set[String]): String =
    elements.foldRight(".setEmpty"): (elem, acc) =>
      s"(.setInsert ${renderExpr(elem, enumNames)} $acc)"

  private def quote(s: String): String =
    val escaped = s.replace("\\", "\\\\").replace("\"", "\\\"")
    s"\"$escaped\""

  private def renderStringList(xs: List[String]): String =
    xs.map(quote).mkString("[", ", ", "]")

  private def sanitize(s: String): String =
    s.flatMap: c =>
      if c.isLetterOrDigit || c == '_' then c.toString else "_"

  private def sanitizeModule(s: String): String =
    val cleaned = sanitize(s)
    if cleaned.isEmpty || !cleaned.head.isLetter then "Spec" + cleaned
    else cleaned
