package specrest.verify.cert

import specrest.ir.*

object Emit:

  final case class CertificateBundle(
      header: String,
      theorems: List[String],
      summary: BundleSummary
  ):
    def render: String =
      val body = if theorems.isEmpty then "  -- no certifiable obligations\n"
      else theorems.mkString("\n\n")
      s"$header\n\n$body\n"

  final case class BundleSummary(
      totalInvariants: Int,
      certifiedInvariants: Int,
      stubbedInvariants: Int
  )

  def emit(ir: ServiceIR): CertificateBundle =
    val (theorems, certifiedCount, stubbedCount) =
      ir.invariants.zipWithIndex.foldLeft((List.empty[String], 0, 0)):
        case ((accThms, c, s), (inv, idx)) =>
          val theoremText = renderInvariantTheorem(ir, inv, idx)
          val (cInc, sInc) = VerifiedSubset.classify(inv.expr) match
            case VerifiedSubset.SubsetStatus.InSubset       => (1, 0)
            case _: VerifiedSubset.SubsetStatus.OutOfSubset => (0, 1)
          (theoremText :: accThms, c + cInc, s + sInc)

    val header = renderHeader(ir)
    CertificateBundle(
      header = header,
      theorems = theorems.reverse,
      summary = BundleSummary(
        totalInvariants = ir.invariants.size,
        certifiedInvariants = certifiedCount,
        stubbedInvariants = stubbedCount
      )
    )

  private def renderHeader(ir: ServiceIR): String =
    s"""import SpecRest.IR
       |import SpecRest.Semantics
       |import SpecRest.Lemmas
       |import SpecRest.Cert
       |
       |/-! # Translation-validation certificate for service `${ir.name}`.
       |
       |    Generated by `specrest.verify.cert.Emit` from the M_L.1
       |    verified-subset Lean embedding. Each theorem closes a closed-
       |    evaluation goal via `cert_decide` (= `native_decide`).
       |
       |    Trust closure: M_L.1 + the `Lean.ofReduceBool` axiom that
       |    `native_decide` introduces. -/
       |
       |namespace SpecRest.Cert.Generated
       |
       |open SpecRest
       |open SpecRest.Cert""".stripMargin

  private def renderInvariantTheorem(
      ir: ServiceIR,
      inv: InvariantDecl,
      idx: Int
  ): String =
    val displayName = inv.name.getOrElse(s"anon_$idx")
    val theoremName = s"cert_invariant_${idx}_${sanitize(displayName)}"
    VerifiedSubset.classify(inv.expr) match
      case VerifiedSubset.SubsetStatus.InSubset =>
        val state   = renderInitialState(ir.state)
        val schema  = renderSchema(ir)
        val invTerm = renderInvariantDecl(inv, displayName)
        s"""/-- Invariant `$displayName` for service `${ir.name}`. -/
           |theorem $theoremName :
           |    evalInvariant
           |        $schema
           |        $state
           |        []
           |        $invTerm
           |      = some true := by
           |  cert_decide""".stripMargin
      case VerifiedSubset.SubsetStatus.OutOfSubset(reason) =>
        s"""/-- Invariant `$displayName` for service `${ir.name}` —
           |    OUT OF M_L.1 VERIFIED SUBSET: $reason. -/
           |theorem $theoremName :
           |    True := by
           |  trivial
           |
           |-- TODO[M_L.4]: $reason — re-emit this certificate once the
           |-- relevant operator joins the verified subset.""".stripMargin

  private def renderSchema(ir: ServiceIR): String =
    if ir.enums.isEmpty && ir.entities.isEmpty then "Schema.empty"
    else
      val enumLits = ir.enums
        .map(d => s"""{ name := ${quote(d.name)}, members := ${renderStringList(d.values)} }""")
        .mkString(", ")
      val entityLits = ir.entities
        .map(d => s"""{ name := ${quote(d.name)}, fields := [] }""")
        .mkString(", ")
      s"""({ enums := [$enumLits], entities := [$entityLits] } : Schema)"""

  private def renderInitialState(state: Option[StateDecl]): String = state match
    case None => "(State.empty)"
    case Some(decl) =>
      val scalars = decl.fields
        .map: f =>
          val v = defaultValueLit(f.typeExpr)
          s"""(${quote(f.name)}, $v)"""
        .mkString(", ")
      s"""({ scalars := [$scalars], relations := [] } : State)"""

  private def renderInvariantDecl(inv: InvariantDecl, displayName: String): String =
    val body = renderExpr(inv.expr)
    s"""({ name := ${quote(displayName)}, body := $body } : InvariantDecl)"""

  private def renderExpr(expr: Expr): String = expr match
    case Expr.BoolLit(v, _)               => s".boolLit $v"
    case Expr.IntLit(v, _)                => s".intLit ($v : Int)"
    case Expr.Identifier(name, _)         => s""".ident ${quote(name)}"""
    case Expr.UnaryOp(UnOp.Not, op, _)    => s"(.unNot ${renderExpr(op)})"
    case Expr.UnaryOp(UnOp.Negate, op, _) => s"(.unNeg ${renderExpr(op)})"
    case Expr.BinaryOp(op, l, r, _) =>
      val lT = renderExpr(l)
      val rT = renderExpr(r)
      op match
        case BinOp.And     => s"(.boolBin .and $lT $rT)"
        case BinOp.Or      => s"(.boolBin .or $lT $rT)"
        case BinOp.Implies => s"(.boolBin .implies $lT $rT)"
        case BinOp.Iff     => s"(.boolBin .iff $lT $rT)"
        case BinOp.Eq      => s"(.cmp .eq $lT $rT)"
        case BinOp.Neq     => s"(.cmp .neq $lT $rT)"
        case BinOp.Lt      => s"(.cmp .lt $lT $rT)"
        case BinOp.Le      => s"(.cmp .le $lT $rT)"
        case BinOp.Gt      => s"(.cmp .gt $lT $rT)"
        case BinOp.Ge      => s"(.cmp .ge $lT $rT)"
        case BinOp.In =>
          r match
            case Expr.Identifier(rel, _) => s"(.member $lT ${quote(rel)})"
            case _                       => "/- BinaryOp(In) requires a relation identifier on the rhs -/"
        case _ => s"/- BinaryOp.$op out of subset -/"
    case Expr.Let(v, value, body, _) =>
      s"(.letIn ${quote(v)} ${renderExpr(value)} ${renderExpr(body)})"
    case Expr.EnumAccess(Expr.Identifier(en, _), member, _) =>
      s"(.enumAccess ${quote(en)} ${quote(member)})"
    case Expr.Quantifier(QuantKind.All, bindings, body, _) =>
      bindings match
        case List(QuantifierBinding(v, Expr.Identifier(en, _), _, _)) =>
          s"(.forallEnum ${quote(v)} ${quote(en)} ${renderExpr(body)})"
        case _ =>
          "/- Quantifier(All): only single-binding over enum identifier supported -/"
    case _ =>
      "/- expression out of M_L.1 verified subset -/"

  private def defaultValueLit(ty: TypeExpr): String = ty match
    case TypeExpr.NamedType("Int", _)  => ".vInt 0"
    case TypeExpr.NamedType("Bool", _) => ".vBool false"
    case TypeExpr.NamedType(other, _)  => s""".vEnum ${quote(other)} "" /- placeholder default -/"""
    case _                             => """.vBool false /- default placeholder -/"""

  private def quote(s: String): String =
    val escaped = s.replace("\\", "\\\\").replace("\"", "\\\"")
    s"\"$escaped\""

  private def renderStringList(xs: List[String]): String =
    xs.map(quote).mkString("[", ", ", "]")

  private def sanitize(s: String): String =
    s.flatMap: c =>
      if c.isLetterOrDigit || c == '_' then c.toString else "_"
