addSbtPlugin("com.simplytyped"    % "sbt-antlr4"       % "0.8.3")
addSbtPlugin("org.scalameta"      % "sbt-native-image" % "0.3.4")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"     % "2.5.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"     % "0.12.1")
addSbtPlugin("org.typelevel"      % "sbt-tpolecat"     % "0.5.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"          % "0.4.8")
