addSbtPlugin("com.simplytyped"    % "sbt-antlr4"       % "0.8.3")
addSbtPlugin("org.scalameta"      % "sbt-native-image" % "0.3.4")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"     % "2.5.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"     % "0.14.6")
addSbtPlugin("org.typelevel"      % "sbt-tpolecat"     % "0.5.3")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"          % "0.4.8")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"    % "2.4.4")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"  % "3.4.3")
