// Auto-generated by spec-to-rest. Do not edit by hand.
//
// Bearer-guarded admin surface (state export / data import / re-initialize).
// The conformance suite (tests/) is its primary client; the contract
// (reset / state / seed) is identical across the fastapi/express targets.

package admin

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/uptrace/bun"
)

func join(xs []string) string { return strings.Join(xs, ", ") }

func placeholders(n int, pg bool) string {
	ps := make([]string, n)
	for i := 0; i < n; i++ {
		if pg {
			ps[i] = fmt.Sprintf("$%d", i+1)
		} else {
			ps[i] = "?"
		}
	}
	return strings.Join(ps, ", ")
}

func normalize(v any) any {
	switch x := v.(type) {
	case []byte:
		return normalizeText(string(x))
	case string:
		return normalizeText(x)
	case time.Time:
		return x.UTC().Format(time.RFC3339)
	default:
		return v
	}
}

// A JSON-typed column comes back as its serialized text; the state
// projection must expose the real array or object, not the string.
func normalizeText(s string) any {
	trimmed := strings.TrimSpace(s)
	if strings.HasPrefix(trimmed, "[") || strings.HasPrefix(trimmed, "{") {
		var decoded any
		if err := json.Unmarshal([]byte(trimmed), &decoded); err == nil {
			return decoded
		}
	}
	return s
}

func queryAll(ctx context.Context, db *bun.DB, q string) ([]map[string]any, error) {
	rows, err := db.QueryContext(ctx, q)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	cols, err := rows.Columns()
	if err != nil {
		return nil, err
	}
	out := make([]map[string]any, 0)
	for rows.Next() {
		vals := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return nil, err
		}
		m := map[string]any{}
		for i, c := range cols {
			m[c] = normalize(vals[i])
		}
		out = append(out, m)
	}
	return out, rows.Err()
}

func Register(r chi.Router, db *bun.DB, guard func(http.Handler) http.Handler) {
	r.With(guard).Post("/admin/reset", func(w http.ResponseWriter, req *http.Request) {
		ctx := req.Context()
		_ = ctx
		if _, err := db.ExecContext(ctx, "DELETE FROM url_mappings"); err != nil {
			http.Error(w, err.Error(), 500)
			return
		}
		w.WriteHeader(204)
	})

	r.With(guard).Get("/admin/state", func(w http.ResponseWriter, req *http.Request) {
		ctx := req.Context()
		_ = ctx
		state := map[string]any{}
		{
			rows, err := queryAll(ctx, db, "SELECT * FROM url_mappings")
			if err != nil {
				http.Error(w, err.Error(), 500)
				return
			}
			m := map[string]any{}
			for _, row := range rows {
				m[fmt.Sprintf("%v", row["code"])] = row["url"]
			}
			state["store"] = m
		}
		{
			rows, err := queryAll(ctx, db, "SELECT * FROM url_mappings")
			if err != nil {
				http.Error(w, err.Error(), 500)
				return
			}
			m := map[string]any{}
			for _, row := range rows {
				m[fmt.Sprintf("%v", row["code"])] = row
			}
			state["metadata"] = m
		}
		state["base_url"] = nil
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		_ = json.NewEncoder(w).Encode(state)
	})
}
