// Auto-generated by spec-to-rest --with-tests. Do not edit by hand.
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    // Conformance tests hit a live service over HTTP; property-based phases run
    // many cases, so the per-test budget is generous.
    testTimeout: 120_000,
    hookTimeout: 60_000,
    fileParallelism: false,
    reporters: ["default", "junit"],
    outputFile: { junit: "results/conformance.xml" },
  },
});
