//go:build conformance

// Auto-generated by spec-to-rest. Do not edit by hand.
//
// Black-box HTTP client for the booted service. Mirrors the Python conftest
// `client` contract: verb methods returning a response with Status() and
// JSON(). The /admin router requires ADMIN_TOKEN (exported to both the
// service and this process); ensureAdmin is the fail-fast guard.

package tests

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"os"
	"testing"
)

var baseURL = func() string {
	if v := os.Getenv("SPEC_TEST_BASE_URL"); v != "" {
		return v
	}
	return "http://localhost:8080"
}()

var adminToken = os.Getenv("ADMIN_TOKEN")

// confStepCount is the stateful random-sequence length per profile, mirroring
// the TypeScript _STEPS map (rapid.Check iteration count is profile-tuned in
// TestMain via the -rapid.checks flag).
func confStepCount() int {
	switch os.Getenv("SPEC_TEST_PROFILE") {
	case "smoke":
		return 8
	case "exhaustive":
		return 40
	default:
		return 20
	}
}

type clientResponse struct {
	status int
	body   []byte
}

func (r clientResponse) Status() int { return r.status }

func (r clientResponse) JSON() any {
	if len(r.body) == 0 {
		return map[string]any{}
	}
	var v any
	if err := json.Unmarshal(r.body, &v); err != nil {
		return map[string]any{}
	}
	return v
}

func httpDo(method, path string, body any) clientResponse {
	var rdr io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return clientResponse{status: -1}
		}
		rdr = bytes.NewReader(b)
	}
	req, err := http.NewRequest(method, baseURL+path, rdr)
	if err != nil {
		return clientResponse{status: -1}
	}
	if body != nil {
		req.Header.Set("content-type", "application/json")
	}
	if adminToken != "" {
		req.Header.Set("Authorization", "Bearer "+adminToken)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return clientResponse{status: -1}
	}
	defer func() { _ = resp.Body.Close() }()
	buf, _ := io.ReadAll(resp.Body)
	return clientResponse{status: resp.StatusCode, body: buf}
}

type httpClient struct{}

func (httpClient) get(p string) clientResponse { return httpDo("GET", p, nil) }

func (httpClient) post(p string, body ...any) clientResponse {
	var b any
	if len(body) > 0 {
		b = body[0]
	}
	return httpDo("POST", p, b)
}

func (httpClient) put(p string, body ...any) clientResponse {
	var b any
	if len(body) > 0 {
		b = body[0]
	}
	return httpDo("PUT", p, b)
}

func (httpClient) patch(p string, body ...any) clientResponse {
	var b any
	if len(body) > 0 {
		b = body[0]
	}
	return httpDo("PATCH", p, b)
}

func (httpClient) delete(p string) clientResponse { return httpDo("DELETE", p, nil) }

var client = httpClient{}

func adminState() any {
	return client.get("/admin/state").JSON()
}

// ensureAdmin resets state and fails fast (clear reason) when the /admin
// router is unreachable or the credential is wrong. Behavioral/stateful tests
// call it at the top of each test so every property starts from a clean,
// reachable state.
func ensureAdmin(t *testing.T) {
	t.Helper()
	r := client.post("/admin/reset")
	switch r.status {
	case 204:
		return
	case -1:
		t.Fatalf("service unreachable at %s: the /admin router is required", baseURL)
	case 404:
		t.Fatalf("/admin answered 404: the service has no ADMIN_TOKEN configured; " +
			"export ADMIN_TOKEN and restart the server with the same value")
	case 401:
		t.Fatalf("/admin rejected the credential (401): ADMIN_TOKEN is missing from " +
			"the test environment or differs from the one the server was started with")
	default:
		t.Fatalf("admin /admin/reset returned %d; service not M5.1-ready", r.status)
	}
}
