//go:build conformance

// Auto-generated by spec-to-rest --with-tests. Do not edit by hand.
//
// Sensitive-field handling. rapid has no value-tagging analog to Python's
// _RedactedStr, so redaction is generation-only: the value is still exercised,
// just never logged as a known secret (see genRedact in conf_gen.go).
// Schemathesis-style request-body redaction for the structural phase is
// tracked by the native structural-lite work (#175).

package conformance

const REDACTED = "***REDACTED***"
