//go:build conformance

// Auto-generated by spec-to-rest. Do not edit by hand.
//
// Runtime helpers the generated assertions call. Go is statically typed, so
// the set/relation/arithmetic semantics Python gets from built-ins (`in`, `==`
// on sets, `<`, `+`, `|`/`&`/`-`, powerset) are delegated here, operating over
// `any` values decoded from /admin/state and response bodies
// (objects -> map[string]any, arrays -> []any, numbers -> json.Number, the
// client decodes with UseNumber). Equality and ordering compare integral
// values exactly as int64, the widest integer the service side can hold (Go
// int64, sqlite INTEGER); fractional values compare as float64, and
// arithmetic stays float64. `_Set` is a named slice so equality is
// order-independent for sets and ordered for sequences, matching the
// TypeScript Set-vs-Array distinction.

package tests

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

type _Set []any

func _toF(x any) (float64, bool) {
	switch v := x.(type) {
	case int:
		return float64(v), true
	case int32:
		return float64(v), true
	case int64:
		return float64(v), true
	case float32:
		return float64(v), true
	case float64:
		return v, true
	case json.Number:
		if f, err := v.Float64(); err == nil {
			return f, true
		}
		return 0, false
	default:
		return 0, false
	}
}

// _toI reports x as an exact int64. json.Number and digit strings (JSON
// object keys of Int-keyed relations) parse directly, skipping the float64
// round-trip that conflates neighbors above 2^53; integral floats convert
// when in int64 range. Integers past int64 cannot originate from the service
// side (Go ints and sqlite INTEGER are 64-bit), so callers fall back to
// float64 for whatever fails here.
func _toI(x any) (int64, bool) {
	switch v := x.(type) {
	case int:
		return int64(v), true
	case int32:
		return int64(v), true
	case int64:
		return v, true
	case json.Number:
		i, err := strconv.ParseInt(v.String(), 10, 64)
		return i, err == nil
	case string:
		i, err := strconv.ParseInt(v, 10, 64)
		return i, err == nil
	case float32:
		return _floatToI(float64(v))
	case float64:
		return _floatToI(v)
	default:
		return 0, false
	}
}

func _floatToI(f float64) (int64, bool) {
	// 2^63 is exact in float64 and one past int64 max, hence the >=. NaN
	// fails the Trunc self-equality; infinities fail the range checks.
	if f != math.Trunc(f) || f < -(1<<63) || f >= 1<<63 {
		return 0, false
	}
	return int64(f), true
}

// Integral numbers share one canonical string regardless of representation
// (json.Number, int64, integral float64), so map-key lookups and hashes
// agree across decoded and computed values.
func _str(x any) string {
	if s, ok := x.(string); ok {
		return s
	}
	if i, ok := _toI(x); ok {
		return strconv.FormatInt(i, 10)
	}
	if f, ok := _toF(x); ok {
		return fmt.Sprintf("%v", f)
	}
	return fmt.Sprintf("%v", x)
}

func _slice(x any) []any {
	switch v := x.(type) {
	case _Set:
		return []any(v)
	case []any:
		return v
	case string:
		out := make([]any, 0, len(v))
		for _, r := range v {
			out = append(out, string(r))
		}
		return out
	case map[string]any:
		keys := make([]string, 0, len(v))
		for k := range v {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		out := make([]any, 0, len(keys))
		for _, k := range keys {
			out = append(out, v[k])
		}
		return out
	default:
		return []any{}
	}
}

// Spec quantifiers over a relation range over its domain: `all c in store`
// binds keys, and the body indexes store[c]. _slice keeps value semantics for
// comprehension-style consumers; quantifier lowering routes through this.
func _quantDomain(x any) []any {
	if m, ok := x.(map[string]any); ok {
		keys := make([]string, 0, len(m))
		for k := range m {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		out := make([]any, 0, len(keys))
		for _, k := range keys {
			out = append(out, k)
		}
		return out
	}
	return _slice(x)
}

func _dedupe(xs []any) []any {
	out := make([]any, 0, len(xs))
	for _, x := range xs {
		dup := false
		for _, y := range out {
			if _eq(x, y) {
				dup = true
				break
			}
		}
		if !dup {
			out = append(out, x)
		}
	}
	return out
}

func _set(xs ...any) any {
	return _Set(_dedupe(xs))
}

func _truthy(x any) bool {
	switch v := x.(type) {
	case bool:
		return v
	case nil:
		return false
	default:
		return false
	}
}

func _eq(a, b any) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	if _, oka := _toF(a); oka {
		return _numEq(a, b)
	}
	if _, oka := a.(string); oka {
		if _, okb := _toF(b); okb {
			return _numEq(a, b)
		}
	}
	switch av := a.(type) {
	case string:
		bv, ok := b.(string)
		return ok && av == bv
	case bool:
		bv, ok := b.(bool)
		return ok && av == bv
	case _Set:
		bv, ok := b.(_Set)
		if !ok || len(av) != len(bv) {
			return false
		}
		for _, x := range av {
			found := false
			for _, y := range bv {
				if _eq(x, y) {
					found = true
					break
				}
			}
			if !found {
				return false
			}
		}
		return true
	case []any:
		bv, ok := b.([]any)
		if !ok || len(av) != len(bv) {
			return false
		}
		for i := range av {
			if !_eq(av[i], bv[i]) {
				return false
			}
		}
		return true
	case map[string]any:
		bv, ok := b.(map[string]any)
		if !ok || len(av) != len(bv) {
			return false
		}
		for k, x := range av {
			y, present := bv[k]
			if !present || !_eq(x, y) {
				return false
			}
		}
		return true
	default:
		return false
	}
}

// Number-vs-number and number-vs-digit-string equality (JSON object keys
// stringify, so an Int-keyed relation iterates as digit strings while ids
// stay numbers). Integral pairs compare exactly as int64: json.Number keeps
// full precision past 2^53, where the float64 round-trip conflates adjacent
// integers. Fractional operands, and integers past int64 (which the service
// side cannot produce), fall back to float64.
func _numEq(a, b any) bool {
	if ia, oka := _toI(a); oka {
		if ib, okb := _toI(b); okb {
			return ia == ib
		}
	}
	fa, oka := _num(a)
	fb, okb := _num(b)
	return oka && okb && fa == fb
}

func _in(x, c any) bool {
	switch cv := c.(type) {
	case string:
		return strings.Contains(cv, _str(x))
	case map[string]any:
		_, ok := cv[_str(x)]
		return ok
	default:
		for _, e := range _slice(c) {
			if _eq(e, x) {
				return true
			}
		}
		return false
	}
}

// Float-context coercion for numbers and numeric strings (JSON object keys).
// Exact integral comparison goes through _toI first; this is the fallback
// for fractional values, where float64 is the spec's own numeric domain.
func _num(x any) (float64, bool) {
	if f, ok := _toF(x); ok {
		return f, true
	}
	if s, ok := x.(string); ok {
		if f, err := strconv.ParseFloat(s, 64); err == nil {
			return f, true
		}
	}
	return 0, false
}

// Set equality for set-typed positions: JSON carries sets as arrays that
// may hold duplicates the set semantics collapse, so compare mutual
// containment, not multisets.
func _setEq(a, b any) bool {
	as := _slice(a)
	bs := _slice(b)
	contains := func(xs []any, v any) bool {
		for _, x := range xs {
			if _eq(x, v) {
				return true
			}
		}
		return false
	}
	for _, x := range as {
		if !contains(bs, x) {
			return false
		}
	}
	for _, y := range bs {
		if !contains(as, y) {
			return false
		}
	}
	return true
}

func _cmp(a, b any) (int, bool) {
	if ia, oka := _toI(a); oka {
		if ib, okb := _toI(b); okb {
			switch {
			case ia < ib:
				return -1, true
			case ia > ib:
				return 1, true
			default:
				return 0, true
			}
		}
	}
	if fa, oka := _num(a); oka {
		if fb, okb := _num(b); okb {
			switch {
			case fa < fb:
				return -1, true
			case fa > fb:
				return 1, true
			default:
				return 0, true
			}
		}
	}
	if sa, oka := a.(string); oka {
		if sb, okb := b.(string); okb {
			return strings.Compare(sa, sb), true
		}
	}
	return 0, false
}

func _lt(a, b any) bool { c, ok := _cmp(a, b); return ok && c < 0 }
func _gt(a, b any) bool { c, ok := _cmp(a, b); return ok && c > 0 }
func _le(a, b any) bool { c, ok := _cmp(a, b); return ok && c <= 0 }
func _ge(a, b any) bool { c, ok := _cmp(a, b); return ok && c >= 0 }

func _add(a, b any) any {
	if fa, oka := _toF(a); oka {
		if fb, okb := _toF(b); okb {
			return fa + fb
		}
	}
	if sa, oka := a.(string); oka {
		if sb, okb := b.(string); okb {
			return sa + sb
		}
	}
	return nil
}

func _sub(a, b any) any {
	fa, oka := _toF(a)
	fb, okb := _toF(b)
	if oka && okb {
		return fa - fb
	}
	return nil
}

func _mul(a, b any) any {
	fa, oka := _toF(a)
	fb, okb := _toF(b)
	if oka && okb {
		return fa * fb
	}
	return nil
}

func _div(a, b any) any {
	fa, oka := _toF(a)
	fb, okb := _toF(b)
	if oka && okb && fb != 0 {
		return fa / fb
	}
	return nil
}

func _neg(a any) any {
	if f, ok := _toF(a); ok {
		return -f
	}
	return nil
}

func _len(x any) any {
	switch v := x.(type) {
	case _Set:
		return int64(len(v))
	case []any:
		return int64(len(v))
	case string:
		return int64(len([]rune(v)))
	case map[string]any:
		return int64(len(v))
	default:
		return int64(0)
	}
}

func _union(a, b any) any {
	return _Set(_dedupe(append(append([]any{}, _slice(a)...), _slice(b)...)))
}

func _inter(a, b any) any {
	bs := _slice(b)
	out := make([]any, 0)
	for _, x := range _slice(a) {
		for _, y := range bs {
			if _eq(x, y) {
				out = append(out, x)
				break
			}
		}
	}
	return _Set(_dedupe(out))
}

func _diff(a, b any) any {
	bs := _slice(b)
	out := make([]any, 0)
	for _, x := range _slice(a) {
		found := false
		for _, y := range bs {
			if _eq(x, y) {
				found = true
				break
			}
		}
		if !found {
			out = append(out, x)
		}
	}
	return _Set(_dedupe(out))
}

func _subset(a, b any) bool {
	bs := _slice(b)
	for _, x := range _slice(a) {
		found := false
		for _, y := range bs {
			if _eq(x, y) {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	return true
}

func _powerset(x any) any {
	items := _dedupe(_slice(x))
	n := len(items)
	subsets := make([]any, 0, 1<<n)
	for mask := 0; mask < (1 << n); mask++ {
		sub := make([]any, 0, n)
		for i := 0; i < n; i++ {
			if mask&(1<<i) != 0 {
				sub = append(sub, items[i])
			}
		}
		subsets = append(subsets, _Set(sub))
	}
	return _Set(subsets)
}

func _field(obj, key any) any {
	if m, ok := obj.(map[string]any); ok {
		return m[_str(key)]
	}
	return nil
}

func _index(base, idx any) any {
	switch b := base.(type) {
	case []any:
		if f, ok := _toF(idx); ok {
			i := int(f)
			if i >= 0 && i < len(b) {
				return b[i]
			}
		}
	case _Set:
		if f, ok := _toF(idx); ok {
			i := int(f)
			if i >= 0 && i < len(b) {
				return b[i]
			}
		}
	case map[string]any:
		return b[_str(idx)]
	case string:
		if f, ok := _toF(idx); ok {
			rs := []rune(b)
			i := int(f)
			if i >= 0 && i < len(rs) {
				return string(rs[i])
			}
		}
	}
	return nil
}

func _keys(x any) any {
	if m, ok := x.(map[string]any); ok {
		ks := make([]string, 0, len(m))
		for k := range m {
			ks = append(ks, k)
		}
		sort.Strings(ks)
		out := make([]any, 0, len(ks))
		for _, k := range ks {
			out = append(out, k)
		}
		return _Set(out)
	}
	return _Set{}
}

func _values(x any) any {
	return _Set(_dedupe(_slice(x)))
}

func _all(coll any, f func(any) bool) bool {
	for _, x := range _slice(coll) {
		if !f(x) {
			return false
		}
	}
	return true
}

func _any(coll any, f func(any) bool) bool {
	for _, x := range _slice(coll) {
		if f(x) {
			return true
		}
	}
	return false
}

func _setFilter(coll any, f func(any) bool) any {
	out := make([]any, 0)
	for _, x := range _slice(coll) {
		if f(x) {
			out = append(out, x)
		}
	}
	return _Set(_dedupe(out))
}

func _find(coll any, f func(any) bool) any {
	for _, x := range _slice(coll) {
		if f(x) {
			return x
		}
	}
	return nil
}

func _max(x any) any {
	s := _slice(x)
	if len(s) == 0 {
		return nil
	}
	best := s[0]
	for _, v := range s[1:] {
		if _gt(v, best) {
			best = v
		}
	}
	return best
}

func _min(x any) any {
	s := _slice(x)
	if len(s) == 0 {
		return nil
	}
	best := s[0]
	for _, v := range s[1:] {
		if _lt(v, best) {
			best = v
		}
	}
	return best
}

func _sum(coll any, f func(any) any) any {
	total := 0.0
	for _, x := range _slice(coll) {
		if v, ok := _toF(f(x)); ok {
			total += v
		}
	}
	return total
}

func _merge(a, b any) any {
	out := map[string]any{}
	if am, ok := a.(map[string]any); ok {
		for k, v := range am {
			out[k] = v
		}
	}
	if bm, ok := b.(map[string]any); ok {
		for k, v := range bm {
			out[k] = v
		}
	}
	return out
}

func _mapOf(kv ...any) any {
	out := map[string]any{}
	for i := 0; i+1 < len(kv); i += 2 {
		out[_str(kv[i])] = kv[i+1]
	}
	return out
}

func _with(base any, kv ...any) any {
	out := map[string]any{}
	if bm, ok := base.(map[string]any); ok {
		for k, v := range bm {
			out[k] = v
		}
	}
	for i := 0; i+1 < len(kv); i += 2 {
		out[_str(kv[i])] = kv[i+1]
	}
	return out
}

func _matches(s any, pat string) bool {
	ok, err := regexp.MatchString(pat, _str(s))
	return err == nil && ok
}

func _call(f any, args ...any) any {
	switch fn := f.(type) {
	case func(any) any:
		if len(args) == 1 {
			return fn(args[0])
		}
	}
	return nil
}

func _abs(x any) any {
	// _toF folds json.Number in; mirrors TS's Math.abs(Number(x)).
	if f, ok := _toF(x); ok {
		return math.Abs(f)
	}
	return math.NaN()
}

func _now() any {
	// Epoch seconds (float64) so `now() - minutes(15)` is numeric arithmetic.
	// Aligns with _mul-based time-unit functions which return numeric seconds.
	return float64(time.Now().UTC().Unix())
}

func _sha256Hex(s any) any {
	// _str canonicalizes numbers (json.Number "2", int64 2, and float64 2
	// all hash as "2") so decoded and computed values agree.
	sum := sha256.Sum256([]byte(_str(s)))
	return hex.EncodeToString(sum[:])
}
