//go:build conformance

// Auto-generated by spec-to-rest --with-tests. Safe to edit: add custom rapid
// generators here (returning *rapid.Generator[any]) and reference them from a
// spec `strategy` convention rule. This stub is only regenerated when absent.

package tests
