//go:build conformance

// Auto-generated by spec-to-rest --with-tests. Do not edit by hand.
//
// rapid (v1.3.0) generator constructors. Every generator yields
// `*rapid.Generator[any]` so heterogeneous spec types compose uniformly under
// Go's static typing, mirroring how the fast-check backend emits concise
// `fc.*` builders.

package conformance

import (
	"math"
	"time"

	"pgregory.net/rapid"
)

func mapAny[T any](g *rapid.Generator[T]) *rapid.Generator[any] {
	return rapid.Map(g, func(x T) any { return any(x) })
}

func genString() *rapid.Generator[any] { return mapAny(rapid.String()) }
func genInt() *rapid.Generator[any]    { return mapAny(rapid.Int64()) }
func genFloat() *rapid.Generator[any] {
	return mapAny(rapid.Float64Range(-1e9, 1e9))
}
func genBool() *rapid.Generator[any] { return mapAny(rapid.Bool()) }

func genDatetime() *rapid.Generator[any] {
	return rapid.Custom(func(t *rapid.T) any {
		epoch := rapid.Int64Range(0, 4102444800).Draw(t, "epoch")
		return time.Unix(epoch, 0).UTC().Format(time.RFC3339)
	})
}
func genJSONDatetime() *rapid.Generator[any] { return genDatetime() }

func genDuration() *rapid.Generator[any] {
	return mapAny(rapid.Float64Range(0, 1e6))
}
func genJSONDuration() *rapid.Generator[any] { return genDuration() }

func genID() *rapid.Generator[any] {
	return mapAny(rapid.StringMatching(
		`[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}`,
	))
}

func genNone() *rapid.Generator[any]    { return rapid.Just(any(nil)) }
func genNothing() *rapid.Generator[any] { return rapid.Just(any(nil)) }

func genOption(inner *rapid.Generator[any]) *rapid.Generator[any] {
	return rapid.OneOf(genNone(), inner)
}

func genSet(inner *rapid.Generator[any]) *rapid.Generator[any] {
	return rapid.Map(rapid.SliceOfN(inner, 0, 5), func(xs []any) any {
		return _set(xs...)
	})
}
func genSetUnique(inner *rapid.Generator[any]) *rapid.Generator[any] {
	return genSet(inner)
}
func genSeq(inner *rapid.Generator[any]) *rapid.Generator[any] {
	return rapid.Map(rapid.SliceOfN(inner, 0, 5), func(xs []any) any {
		return xs
	})
}

func genJust(v any) *rapid.Generator[any] { return rapid.Just(v) }

func genSampled(vs ...any) *rapid.Generator[any] {
	return rapid.SampledFrom(vs)
}

func genDict(kv ...any) *rapid.Generator[any] {
	return rapid.Custom(func(t *rapid.T) any {
		out := map[string]any{}
		for i := 0; i+1 < len(kv); i += 2 {
			name, _ := kv[i].(string)
			if g, ok := kv[i+1].(*rapid.Generator[any]); ok {
				out[name] = g.Draw(t, name)
			}
		}
		return out
	})
}

func genRedact(inner *rapid.Generator[any]) *rapid.Generator[any] { return inner }

func genStringMatching(pat string) *rapid.Generator[any] {
	return mapAny(rapid.StringMatching(pat))
}

func genStringBounded(minLen, maxLen int) *rapid.Generator[any] {
	lo := 0
	if minLen > 0 {
		lo = minLen
	}
	hi := -1
	if maxLen >= 0 {
		hi = maxLen
	}
	return mapAny(rapid.StringN(lo, hi, -1))
}

func genFilterLen(g *rapid.Generator[any], lo, hi int) *rapid.Generator[any] {
	return g.Filter(func(x any) bool {
		n := int(_len(x).(int64))
		if lo >= 0 && n < lo {
			return false
		}
		if hi >= 0 && n > hi {
			return false
		}
		return true
	})
}

func genFilterRegex(g *rapid.Generator[any], pat string) *rapid.Generator[any] {
	return g.Filter(func(x any) bool { return _matches(x, pat) })
}

func genFilterPred(g *rapid.Generator[any], pred func(any) any) *rapid.Generator[any] {
	return g.Filter(func(x any) bool { return _truthy(pred(x)) })
}

func genIntRange(lo, hi int64) *rapid.Generator[any] {
	return mapAny(rapid.Int64Range(lo, hi))
}
func genIntMin(lo int64) *rapid.Generator[any] {
	return mapAny(rapid.Int64Range(lo, math.MaxInt64))
}
func genIntMax(hi int64) *rapid.Generator[any] {
	return mapAny(rapid.Int64Range(math.MinInt64, hi))
}
