//go:build conformance

// Auto-generated by spec-to-rest. Do not edit by hand.
//
// Profile-tunes rapid's per-property iteration count (the -rapid.checks flag,
// registered by the rapid package) from SPEC_TEST_PROFILE, mirroring the
// vitest NUM_RUNS map. One TestMain per package; behavioral/stateful/structural
// share it.

package tests

import (
	"flag"
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	checks := "100"
	switch os.Getenv("SPEC_TEST_PROFILE") {
	case "smoke":
		checks = "20"
	case "exhaustive":
		checks = "400"
	}
	flag.Parse()
	if f := flag.Lookup("rapid.checks"); f != nil {
		_ = f.Value.Set(checks)
	}
	os.Exit(m.Run())
}
