package specrest.codegen.ts

import specrest.codegen.AuthSchemes
import specrest.ir.generated.SpecRestGenerated.*
import specrest.profile.ProfiledService

object SecurityTs:

  def middlewareName(requiresAuth: List[String]): String =
    s"require${requiresAuth.map(AuthSchemes.pascalName).mkString("Or")}"

  def schemaLines(ir: ServiceIRFull): List[String] =
    val schemes = svcSecurity(ir)
    val jwtPair =
      if AuthSchemes.needsJwt(ir) then
        List(
          "JWT_SECRET: z.string().optional(),",
          "JWT_ALGORITHM: z.string().default('HS256'),"
        )
      else Nil
    jwtPair ++ schemes.flatMap: s =>
      val u = ssdName(s).toUpperCase
      ssdKind(s) match
        case SsBearer(_) if AuthSchemes.isJwt(ssdKind(s)) => Nil
        case SsBearer(_)                                  => List(s"AUTH_TOKEN_$u: z.string().optional(),")
        case SsApiKey(_, _)                               => List(s"AUTH_KEY_$u: z.string().optional(),")
        case SsBasic() =>
          List(
            s"AUTH_BASIC_${u}_USERNAME: z.string().optional(),",
            s"AUTH_BASIC_${u}_PASSWORD: z.string().optional(),"
          )

  def configLines(ir: ServiceIRFull): List[String] =
    val schemes = svcSecurity(ir)
    val jwtPair =
      if AuthSchemes.needsJwt(ir) then
        List("jwtSecret: parsed.JWT_SECRET,", "jwtAlgorithm: parsed.JWT_ALGORITHM,")
      else Nil
    jwtPair ++ schemes.flatMap: s =>
      val c = AuthSchemes.pascalName(ssdName(s))
      val u = ssdName(s).toUpperCase
      ssdKind(s) match
        case SsBearer(_) if AuthSchemes.isJwt(ssdKind(s)) => Nil
        case SsBearer(_)                                  => List(s"authToken$c: parsed.AUTH_TOKEN_$u,")
        case SsApiKey(_, _)                               => List(s"authKey$c: parsed.AUTH_KEY_$u,")
        case SsBasic() =>
          List(
            s"authBasic${c}Username: parsed.AUTH_BASIC_${u}_USERNAME,",
            s"authBasic${c}Password: parsed.AUTH_BASIC_${u}_PASSWORD,"
          )

  def emit(profiled: ProfiledService): String =
    val ir       = profiled.ir
    val schemes  = svcSecurity(ir)
    val needsJwt = AuthSchemes.needsJwt(ir)
    val needsSafeEqual = schemes.exists(s =>
      ssdKind(s) match
        case SsBearer(_) => !AuthSchemes.isJwt(ssdKind(s))
        case _           => true
    )
    val hasBearer = schemes.exists(s =>
      ssdKind(s) match { case SsBearer(_) => true; case _ => false }
    )
    val needsBasic = schemes.exists(s =>
      ssdKind(s) match { case SsBasic() => true; case _ => false }
    )
    val needsCookie = schemes.exists(s =>
      ssdKind(s) match { case SsApiKey("cookie", _) => true; case _ => false }
    )

    val combos = profiled.operations
      .map(_.requiresAuth)
      .filter(_.sizeIs > 1)
      .distinctBy(middlewareName)

    val helpers = List(
      Option.when(needsSafeEqual)(
        """|const safeEqual = (presented: string, expected: string): boolean => {
           |  const a = Buffer.from(presented);
           |  const b = Buffer.from(expected);
           |  return a.length === b.length && timingSafeEqual(a, b);
           |};""".stripMargin
      ),
      Option.when(hasBearer)(
        """|const bearerToken = (req: Request): string => {
           |  const header = req.get('authorization') ?? '';
           |  return /^bearer /i.test(header) ? header.slice('bearer '.length) : '';
           |};""".stripMargin
      ),
      Option.when(needsBasic)(
        """|const basicCredentials = (req: Request): [string, string] | null => {
           |  const header = req.get('authorization') ?? '';
           |  if (!/^basic /i.test(header)) {
           |    return null;
           |  }
           |  const decoded = Buffer.from(header.slice('basic '.length), 'base64').toString('utf8');
           |  const idx = decoded.indexOf(':');
           |  return idx < 0 ? null : [decoded.slice(0, idx), decoded.slice(idx + 1)];
           |};""".stripMargin
      ),
      Option.when(needsCookie)(
        """|const cookieValue = (req: Request, name: string): string => {
           |  for (const part of (req.headers.cookie ?? '').split(';')) {
           |    const [k, ...rest] = part.trim().split('=');
           |    if (k === name) {
           |      return rest.join('=');
           |    }
           |  }
           |  return '';
           |};""".stripMargin
      )
    ).flatten

    val sections =
      schemes.map(checker) ++
        schemes.map(s => middleware(List(ssdName(s)))) ++
        combos.map(middleware)

    s"""|// Auto-generated by spec-to-rest. Do not edit by hand.
        |//
        |// Spec-declared security schemes (the service's security block). Each
        |// scheme gets a checker and a require* middleware; multi-scheme
        |// requires_auth clauses get a combined middleware with OR semantics.
        |// Everything fails closed: missing credentials or configuration is 401.
        |${if needsSafeEqual then "import { timingSafeEqual } from 'node:crypto';\n" else ""}
        |import type { NextFunction, Request, Response } from 'express';
        |${if needsJwt then "import jwt from 'jsonwebtoken';\n" else ""}
        |import { config } from '../config.js';
        |
        |${helpers.mkString("\n\n")}
        |
        |const unauthorized = (res: Response): void => {
        |  res.set('WWW-Authenticate', 'Bearer').status(401).json({ detail: 'Unauthorized' });
        |};
        |
        |${sections.mkString("\n\n")}
        |""".stripMargin

  private def checker(decl: security_scheme_decl): String =
    val n = ssdName(decl)
    val c = AuthSchemes.pascalName(n)
    ssdKind(decl) match
      case SsBearer(_) if AuthSchemes.isJwt(ssdKind(decl)) =>
        s"""|const check$c = (req: Request): boolean => {
            |  const token = bearerToken(req);
            |  if (token === '' || config.jwtSecret === undefined) {
            |    return false;
            |  }
            |  try {
            |    jwt.verify(token, config.jwtSecret, {
            |      algorithms: [config.jwtAlgorithm as jwt.Algorithm],
            |    });
            |    return true;
            |  } catch {
            |    return false;
            |  }
            |};""".stripMargin
      case SsBearer(_) =>
        s"""|const check$c = (req: Request): boolean => {
            |  const expected = config.authToken$c;
            |  const token = bearerToken(req);
            |  return token !== '' && expected !== undefined && safeEqual(token, expected);
            |};""".stripMargin
      case SsApiKey(location, paramName) =>
        val extract = location match
          case "query" =>
            s"const raw = req.query['$paramName'];\n  const value = typeof raw === 'string' ? raw : '';"
          case "cookie" => s"const value = cookieValue(req, '$paramName');"
          case _        => s"const value = req.get('$paramName') ?? '';"
        s"""|const check$c = (req: Request): boolean => {
            |  $extract
            |  const expected = config.authKey$c;
            |  return value !== '' && expected !== undefined && safeEqual(value, expected);
            |};""".stripMargin
      case SsBasic() =>
        s"""|const check$c = (req: Request): boolean => {
            |  const credentials = basicCredentials(req);
            |  const username = config.authBasic${c}Username;
            |  const password = config.authBasic${c}Password;
            |  return (
            |    credentials !== null
            |    && username !== undefined
            |    && password !== undefined
            |    && safeEqual(credentials[0], username)
            |    && safeEqual(credentials[1], password)
            |  );
            |};""".stripMargin

  private def middleware(names: List[String]): String =
    val checks = names.map(n => s"check${AuthSchemes.pascalName(n)}(req)").mkString(" || ")
    s"""|export const ${middlewareName(names)} = (
        |  req: Request,
        |  res: Response,
        |  next: NextFunction,
        |): void => {
        |  if ($checks) {
        |    next();
        |    return;
        |  }
        |  unauthorized(res);
        |};""".stripMargin
