// Auto-generated by spec-to-rest. Do not edit by hand.
//
// Black-box HTTP client for the booted service. Mirrors the Python conftest
// `client` contract: verb methods returning a response with `.status`, async
// `.json()` and `.text()`. The /admin router requires ADMIN_TOKEN (exported to
// both the service and this process); `ensureAdmin()` is the fail-fast guard.

const BASE_URL = process.env.SPEC_TEST_BASE_URL ?? "http://localhost:8080";
const ADMIN_TOKEN = process.env.ADMIN_TOKEN ?? "";

export interface ClientResponse {
  status: number;
  json(): Promise<unknown>;
  text(): Promise<string>;
}

async function request(
  method: string,
  path: string,
  body?: unknown,
): Promise<ClientResponse> {
  const init: RequestInit = { method };
  const headers: Record<string, string> = {};
  if (ADMIN_TOKEN !== "") {
    headers["authorization"] = `Bearer ${ADMIN_TOKEN}`;
  }
  if (body !== undefined) {
    init.body = JSON.stringify(body);
    headers["content-type"] = "application/json";
  }
  if (Object.keys(headers).length > 0) {
    init.headers = headers;
  }
  const res = await fetch(BASE_URL + path, init);
  const buf = await res.text();
  return {
    status: res.status,
    text: async () => buf,
    json: async () => (buf.length > 0 ? (JSON.parse(buf) as unknown) : {}),
  };
}

export const client = {
  get: (path: string) => request("GET", path),
  post: (path: string, body?: unknown) => request("POST", path, body),
  put: (path: string, body?: unknown) => request("PUT", path, body),
  patch: (path: string, body?: unknown) => request("PATCH", path, body),
  delete: (path: string) => request("DELETE", path),
};

export class AdminUnavailable extends Error {}

// Resolves when the /admin router is reachable and reset succeeds; rejects
// with AdminUnavailable otherwise so the suite fails fast with a clear reason.
export async function ensureAdmin(): Promise<void> {
  let res: ClientResponse;
  try {
    res = await client.post("/admin/reset");
  } catch (e) {
    throw new AdminUnavailable(`service unreachable at ${BASE_URL}: ${String(e)}`);
  }
  if (res.status === 404) {
    throw new AdminUnavailable(
      "/admin answered 404: the service has no ADMIN_TOKEN configured. " +
        "Export ADMIN_TOKEN and restart the service with the same value, " +
        "e.g. ADMIN_TOKEN=$(openssl rand -hex 32) npm start",
    );
  }
  if (res.status === 401) {
    throw new AdminUnavailable(
      "/admin rejected the credential (401): ADMIN_TOKEN is missing from the " +
        "test environment or differs from the one the service was started with",
    );
  }
  if (res.status !== 204) {
    throw new AdminUnavailable(
      `admin /admin/reset returned ${res.status}; service not M5.1-ready`,
    );
  }
}
