// Auto-generated by spec-to-rest --with-tests. Do not edit by hand.
//
// Black-box HTTP client for the booted service. Mirrors the Python conftest
// `client` contract: verb methods returning a response with `.status`, async
// `.json()` and `.text()`. The test-admin router (ENABLE_TEST_ADMIN=1) must be
// mounted; `ensureAdmin()` is the fail-fast reachability guard.

const BASE_URL = process.env.SPEC_TEST_BASE_URL ?? "http://localhost:8080";

export interface ClientResponse {
  status: number;
  json(): Promise<unknown>;
  text(): Promise<string>;
}

async function request(
  method: string,
  path: string,
  body?: unknown,
): Promise<ClientResponse> {
  const init: RequestInit = { method };
  if (body !== undefined) {
    init.body = JSON.stringify(body);
    init.headers = { "content-type": "application/json" };
  }
  const res = await fetch(BASE_URL + path, init);
  const buf = await res.text();
  return {
    status: res.status,
    text: async () => buf,
    json: async () => (buf.length > 0 ? (JSON.parse(buf) as unknown) : {}),
  };
}

export const client = {
  get: (path: string) => request("GET", path),
  post: (path: string, body?: unknown) => request("POST", path, body),
  put: (path: string, body?: unknown) => request("PUT", path, body),
  patch: (path: string, body?: unknown) => request("PATCH", path, body),
  delete: (path: string) => request("DELETE", path),
};

export class AdminUnavailable extends Error {}

// Resolves when the test-admin router is reachable and reset succeeds; rejects
// with AdminUnavailable otherwise so the suite fails fast with a clear reason.
export async function ensureAdmin(): Promise<void> {
  let res: ClientResponse;
  try {
    res = await client.post("/__test_admin__/reset");
  } catch (e) {
    throw new AdminUnavailable(`service unreachable at ${BASE_URL}: ${String(e)}`);
  }
  if (res.status === 403) {
    throw new AdminUnavailable(
      "ENABLE_TEST_ADMIN=1 is not set on the service; the test-admin router " +
        "is required. Restart with: ENABLE_TEST_ADMIN=1 npm start",
    );
  }
  if (res.status !== 204) {
    throw new AdminUnavailable(
      `admin /__test_admin__/reset returned ${res.status}; service not M5.1-ready`,
    );
  }
}
