// Auto-generated by spec-to-rest. Do not edit by hand.
//
// Sensitive-field handling for behavioral/stateful generation. fast-check has
// no value-tagging analog to Python's _RedactedStr, so `redact` is a
// passthrough here: the generated value is still exercised, just never logged
// as a known secret. Schemathesis-style request-body redaction for the
// structural phase is tracked by the native structural-lite work (#175).

import type { Arbitrary } from "fast-check";

export const REDACTED = "***REDACTED***";

export function redact<T>(arb: Arbitrary<T>): Arbitrary<T> {
  return arb;
}
