// Auto-generated by spec-to-rest. Do not edit by hand.
//
// Runtime helpers the generated assertions call. These give TypeScript the
// set/relation semantics Python gets from built-ins (`in`, `==` on sets,
// `len`, `|`/`&`/`-`, powerset). State read from /__test_admin__/state is a
// plain JSON object; relation/map state fields project as `{ key: value }`.

import { createHash } from "node:crypto";

type Anything = unknown;

function asArray(x: Anything): Anything[] {
  if (x instanceof Set || x instanceof Map) return Array.from(x.values());
  if (Array.isArray(x)) return x;
  if (typeof x === "string") return Array.from(x);
  if (x && typeof x === "object") return Object.values(x as Record<string, Anything>);
  return [];
}

export function _len(x: Anything): number {
  if (x instanceof Set || x instanceof Map) return x.size;
  if (Array.isArray(x) || typeof x === "string") return (x as { length: number }).length;
  if (x && typeof x === "object") return Object.keys(x as object).length;
  return 0;
}

export function _eq(a: Anything, b: Anything): boolean {
  if (a === b) return true;
  if (a === null || b === null || a === undefined || b === undefined) return a === b;
  const sa = a instanceof Set ? Array.from(a) : null;
  const sb = b instanceof Set ? Array.from(b) : null;
  if (sa && sb) {
    if (sa.length !== sb.length) return false;
    return sa.every((x) => sb.some((y) => _eq(x, y)));
  }
  if (Array.isArray(a) && Array.isArray(b)) {
    return a.length === b.length && a.every((x, i) => _eq(x, b[i]));
  }
  if (typeof a === "object" && typeof b === "object") {
    const ka = Object.keys(a as object).sort();
    const kb = Object.keys(b as object).sort();
    if (ka.length !== kb.length || !ka.every((k, i) => k === kb[i])) return false;
    return ka.every((k) =>
      _eq((a as Record<string, Anything>)[k], (b as Record<string, Anything>)[k]),
    );
  }
  return false;
}

export function _in(x: Anything, c: Anything): boolean {
  if (typeof c === "string") return c.includes(String(x));
  if (c instanceof Map) return c.has(x);
  if (c && typeof c === "object" && !(c instanceof Set) && !Array.isArray(c)) {
    return Object.prototype.hasOwnProperty.call(c, String(x));
  }
  return asArray(c).some((e) => _eq(e, x));
}

function dedupe(xs: Anything[]): Anything[] {
  const out: Anything[] = [];
  for (const x of xs) if (!out.some((y) => _eq(y, x))) out.push(x);
  return out;
}

export function _union(a: Anything, b: Anything): Set<Anything> {
  return new Set(dedupe([...asArray(a), ...asArray(b)]));
}

export function _inter(a: Anything, b: Anything): Set<Anything> {
  const bs = asArray(b);
  return new Set(dedupe(asArray(a).filter((x) => bs.some((y) => _eq(x, y)))));
}

export function _diff(a: Anything, b: Anything): Set<Anything> {
  const bs = asArray(b);
  return new Set(dedupe(asArray(a).filter((x) => !bs.some((y) => _eq(x, y)))));
}

export function _subset(a: Anything, b: Anything): boolean {
  const bs = asArray(b);
  return asArray(a).every((x) => bs.some((y) => _eq(x, y)));
}

export function _powerset(x: Anything): Set<Set<Anything>> {
  const items = dedupe(asArray(x));
  const subsets: Set<Anything>[] = [];
  for (let mask = 0; mask < 1 << items.length; mask++) {
    const sub: Anything[] = [];
    for (let i = 0; i < items.length; i++) if (mask & (1 << i)) sub.push(items[i]);
    subsets.push(new Set(sub));
  }
  return new Set(subsets);
}

export function _sha256Hex(x: Anything): string {
  return createHash("sha256").update(String(x)).digest("hex");
}
