// Auto-generated by spec-to-rest. Safe to edit: add custom
// fast-check arbitraries here and reference them from a spec `strategy`
// convention rule (target.strategy = "./_strategiesUser:myArb"). This stub is
// only regenerated when absent.

export {};
